# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_CalibrationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AGTCalibrationDialog(object):
    def setupUi(self, AGTCalibrationDialog):
        AGTCalibrationDialog.setObjectName("AGTCalibrationDialog")
        AGTCalibrationDialog.resize(321, 375)
        self.gridLayout_3 = QtWidgets.QGridLayout(AGTCalibrationDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(AGTCalibrationDialog)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.ButtonBrowse = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowse.sizePolicy().hasHeightForWidth())
        self.ButtonBrowse.setSizePolicy(sizePolicy)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName("ButtonBrowse")
        self.gridLayout_4.addWidget(self.ButtonBrowse, 0, 2, 1, 1)
        self.inFileLine = QtWidgets.QLineEdit(self.widget_2)
        self.inFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.inFileLine.setObjectName("inFileLine")
        self.gridLayout_4.addWidget(self.inFileLine, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(AGTCalibrationDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.altSpinBottom = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altSpinBottom.sizePolicy().hasHeightForWidth())
        self.altSpinBottom.setSizePolicy(sizePolicy)
        self.altSpinBottom.setDecimals(2)
        self.altSpinBottom.setSingleStep(0.1)
        self.altSpinBottom.setProperty("value", 0.02)
        self.altSpinBottom.setObjectName("altSpinBottom")
        self.gridLayout.addWidget(self.altSpinBottom, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.altSpinTop = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altSpinTop.sizePolicy().hasHeightForWidth())
        self.altSpinTop.setSizePolicy(sizePolicy)
        self.altSpinTop.setDecimals(2)
        self.altSpinTop.setSingleStep(0.1)
        self.altSpinTop.setProperty("value", 2.0)
        self.altSpinTop.setObjectName("altSpinTop")
        self.gridLayout.addWidget(self.altSpinTop, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(AGTCalibrationDialog)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 2)
        self.meanResist = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meanResist.sizePolicy().hasHeightForWidth())
        self.meanResist.setSizePolicy(sizePolicy)
        self.meanResist.setDecimals(1)
        self.meanResist.setSingleStep(0.1)
        self.meanResist.setProperty("value", 30.0)
        self.meanResist.setObjectName("meanResist")
        self.gridLayout_2.addWidget(self.meanResist, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.layer1Thick = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer1Thick.sizePolicy().hasHeightForWidth())
        self.layer1Thick.setSizePolicy(sizePolicy)
        self.layer1Thick.setDecimals(1)
        self.layer1Thick.setSingleStep(0.1)
        self.layer1Thick.setProperty("value", 0.2)
        self.layer1Thick.setObjectName("layer1Thick")
        self.gridLayout_2.addWidget(self.layer1Thick, 2, 1, 1, 1)
        self.resistL1 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL1.sizePolicy().hasHeightForWidth())
        self.resistL1.setSizePolicy(sizePolicy)
        self.resistL1.setDecimals(1)
        self.resistL1.setMaximum(999.0)
        self.resistL1.setSingleStep(0.1)
        self.resistL1.setProperty("value", 30.0)
        self.resistL1.setObjectName("resistL1")
        self.gridLayout_2.addWidget(self.resistL1, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.layer2Thick = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer2Thick.sizePolicy().hasHeightForWidth())
        self.layer2Thick.setSizePolicy(sizePolicy)
        self.layer2Thick.setDecimals(1)
        self.layer2Thick.setSingleStep(0.1)
        self.layer2Thick.setProperty("value", 0.5)
        self.layer2Thick.setObjectName("layer2Thick")
        self.gridLayout_2.addWidget(self.layer2Thick, 3, 1, 1, 1)
        self.resistL2 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL2.sizePolicy().hasHeightForWidth())
        self.resistL2.setSizePolicy(sizePolicy)
        self.resistL2.setDecimals(1)
        self.resistL2.setMaximum(999.0)
        self.resistL2.setSingleStep(0.1)
        self.resistL2.setProperty("value", 30.0)
        self.resistL2.setObjectName("resistL2")
        self.gridLayout_2.addWidget(self.resistL2, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.layer3Thick = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer3Thick.sizePolicy().hasHeightForWidth())
        self.layer3Thick.setSizePolicy(sizePolicy)
        self.layer3Thick.setDecimals(1)
        self.layer3Thick.setSingleStep(0.1)
        self.layer3Thick.setProperty("value", 1.0)
        self.layer3Thick.setObjectName("layer3Thick")
        self.gridLayout_2.addWidget(self.layer3Thick, 4, 1, 1, 1)
        self.resistL3 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL3.sizePolicy().hasHeightForWidth())
        self.resistL3.setSizePolicy(sizePolicy)
        self.resistL3.setDecimals(1)
        self.resistL3.setMaximum(999.0)
        self.resistL3.setSingleStep(0.1)
        self.resistL3.setProperty("value", 30.0)
        self.resistL3.setObjectName("resistL3")
        self.gridLayout_2.addWidget(self.resistL3, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.layer4Thick = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer4Thick.sizePolicy().hasHeightForWidth())
        self.layer4Thick.setSizePolicy(sizePolicy)
        self.layer4Thick.setDecimals(1)
        self.layer4Thick.setSingleStep(0.1)
        self.layer4Thick.setProperty("value", 2.0)
        self.layer4Thick.setObjectName("layer4Thick")
        self.gridLayout_2.addWidget(self.layer4Thick, 5, 1, 1, 1)
        self.resistL4 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL4.sizePolicy().hasHeightForWidth())
        self.resistL4.setSizePolicy(sizePolicy)
        self.resistL4.setDecimals(1)
        self.resistL4.setMaximum(999.0)
        self.resistL4.setSingleStep(0.1)
        self.resistL4.setProperty("value", 30.0)
        self.resistL4.setObjectName("resistL4")
        self.gridLayout_2.addWidget(self.resistL4, 5, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 0, 1, 1)
        self.resistL5 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL5.sizePolicy().hasHeightForWidth())
        self.resistL5.setSizePolicy(sizePolicy)
        self.resistL5.setDecimals(1)
        self.resistL5.setMaximum(999.0)
        self.resistL5.setSingleStep(0.1)
        self.resistL5.setProperty("value", 30.0)
        self.resistL5.setObjectName("resistL5")
        self.gridLayout_2.addWidget(self.resistL5, 6, 2, 1, 1)
        self.meanResisCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.meanResisCheckBox.setObjectName("meanResisCheckBox")
        self.gridLayout_2.addWidget(self.meanResisCheckBox, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(AGTCalibrationDialog)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_3.addWidget(self.saveButton, 3, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(AGTCalibrationDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_3.addWidget(self.cancelButton, 3, 2, 1, 1)

        self.retranslateUi(AGTCalibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(AGTCalibrationDialog)

    def retranslateUi(self, AGTCalibrationDialog):
        _translate = QtCore.QCoreApplication.translate
        AGTCalibrationDialog.setWindowTitle(_translate("AGTCalibrationDialog", "Calibration"))
        self.label.setText(_translate("AGTCalibrationDialog", "EMI calibration file "))
        self.ButtonBrowse.setText(_translate("AGTCalibrationDialog", "browse"))
        self.label_3.setText(_translate("AGTCalibrationDialog", "Altitude mesure bottom"))
        self.label_4.setText(_translate("AGTCalibrationDialog", "Altitude mesure top"))
        self.label_5.setText(_translate("AGTCalibrationDialog", "Electrical model"))
        self.label_6.setText(_translate("AGTCalibrationDialog", "Thickness"))
        self.label_7.setText(_translate("AGTCalibrationDialog", "Resistivity"))
        self.label_9.setText(_translate("AGTCalibrationDialog", "Layer 1"))
        self.label_10.setText(_translate("AGTCalibrationDialog", "Layer 2"))
        self.label_11.setText(_translate("AGTCalibrationDialog", "Layer 3"))
        self.label_12.setText(_translate("AGTCalibrationDialog", "Layer 4"))
        self.label_13.setText(_translate("AGTCalibrationDialog", "Layer 5"))
        self.meanResisCheckBox.setText(_translate("AGTCalibrationDialog", "Mean resistivity"))
        self.saveButton.setText(_translate("AGTCalibrationDialog", "Save"))
        self.cancelButton.setText(_translate("AGTCalibrationDialog", "Cancel"))

