# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_CalibrationDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AGTCalibrationDialog(object):
    def setupUi(self, AGTCalibrationDialog):
        AGTCalibrationDialog.setObjectName(_fromUtf8("AGTCalibrationDialog"))
        AGTCalibrationDialog.resize(321, 375)
        self.gridLayout_3 = QtGui.QGridLayout(AGTCalibrationDialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.widget_2 = QtGui.QWidget(AGTCalibrationDialog)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.widget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.ButtonBrowse = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowse.sizePolicy().hasHeightForWidth())
        self.ButtonBrowse.setSizePolicy(sizePolicy)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName(_fromUtf8("ButtonBrowse"))
        self.gridLayout_4.addWidget(self.ButtonBrowse, 0, 2, 1, 1)
        self.inFileLine = QtGui.QLineEdit(self.widget_2)
        self.inFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.inFileLine.setObjectName(_fromUtf8("inFileLine"))
        self.gridLayout_4.addWidget(self.inFileLine, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(AGTCalibrationDialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.altSpinBottom = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altSpinBottom.sizePolicy().hasHeightForWidth())
        self.altSpinBottom.setSizePolicy(sizePolicy)
        self.altSpinBottom.setDecimals(2)
        self.altSpinBottom.setSingleStep(0.1)
        self.altSpinBottom.setProperty("value", 0.02)
        self.altSpinBottom.setObjectName(_fromUtf8("altSpinBottom"))
        self.gridLayout.addWidget(self.altSpinBottom, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(107, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.altSpinTop = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altSpinTop.sizePolicy().hasHeightForWidth())
        self.altSpinTop.setSizePolicy(sizePolicy)
        self.altSpinTop.setDecimals(2)
        self.altSpinTop.setSingleStep(0.1)
        self.altSpinTop.setProperty("value", 2.0)
        self.altSpinTop.setObjectName(_fromUtf8("altSpinTop"))
        self.gridLayout.addWidget(self.altSpinTop, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(AGTCalibrationDialog)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 2)
        self.meanResist = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meanResist.sizePolicy().hasHeightForWidth())
        self.meanResist.setSizePolicy(sizePolicy)
        self.meanResist.setDecimals(1)
        self.meanResist.setSingleStep(0.1)
        self.meanResist.setProperty("value", 30.0)
        self.meanResist.setObjectName(_fromUtf8("meanResist"))
        self.gridLayout_2.addWidget(self.meanResist, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.layer1Thick = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer1Thick.sizePolicy().hasHeightForWidth())
        self.layer1Thick.setSizePolicy(sizePolicy)
        self.layer1Thick.setDecimals(1)
        self.layer1Thick.setSingleStep(0.1)
        self.layer1Thick.setProperty("value", 0.2)
        self.layer1Thick.setObjectName(_fromUtf8("layer1Thick"))
        self.gridLayout_2.addWidget(self.layer1Thick, 2, 1, 1, 1)
        self.resistL1 = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL1.sizePolicy().hasHeightForWidth())
        self.resistL1.setSizePolicy(sizePolicy)
        self.resistL1.setDecimals(1)
        self.resistL1.setSingleStep(0.1)
        self.resistL1.setProperty("value", 30.0)
        self.resistL1.setObjectName(_fromUtf8("resistL1"))
        self.gridLayout_2.addWidget(self.resistL1, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.layer2Thick = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer2Thick.sizePolicy().hasHeightForWidth())
        self.layer2Thick.setSizePolicy(sizePolicy)
        self.layer2Thick.setDecimals(1)
        self.layer2Thick.setSingleStep(0.1)
        self.layer2Thick.setProperty("value", 0.5)
        self.layer2Thick.setObjectName(_fromUtf8("layer2Thick"))
        self.gridLayout_2.addWidget(self.layer2Thick, 3, 1, 1, 1)
        self.resistL2 = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL2.sizePolicy().hasHeightForWidth())
        self.resistL2.setSizePolicy(sizePolicy)
        self.resistL2.setDecimals(1)
        self.resistL2.setSingleStep(0.1)
        self.resistL2.setProperty("value", 30.0)
        self.resistL2.setObjectName(_fromUtf8("resistL2"))
        self.gridLayout_2.addWidget(self.resistL2, 3, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.layer3Thick = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer3Thick.sizePolicy().hasHeightForWidth())
        self.layer3Thick.setSizePolicy(sizePolicy)
        self.layer3Thick.setDecimals(1)
        self.layer3Thick.setSingleStep(0.1)
        self.layer3Thick.setProperty("value", 1.0)
        self.layer3Thick.setObjectName(_fromUtf8("layer3Thick"))
        self.gridLayout_2.addWidget(self.layer3Thick, 4, 1, 1, 1)
        self.resistL3 = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL3.sizePolicy().hasHeightForWidth())
        self.resistL3.setSizePolicy(sizePolicy)
        self.resistL3.setDecimals(1)
        self.resistL3.setSingleStep(0.1)
        self.resistL3.setProperty("value", 30.0)
        self.resistL3.setObjectName(_fromUtf8("resistL3"))
        self.gridLayout_2.addWidget(self.resistL3, 4, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.layer4Thick = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layer4Thick.sizePolicy().hasHeightForWidth())
        self.layer4Thick.setSizePolicy(sizePolicy)
        self.layer4Thick.setDecimals(1)
        self.layer4Thick.setSingleStep(0.1)
        self.layer4Thick.setProperty("value", 2.0)
        self.layer4Thick.setObjectName(_fromUtf8("layer4Thick"))
        self.gridLayout_2.addWidget(self.layer4Thick, 5, 1, 1, 1)
        self.resistL4 = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL4.sizePolicy().hasHeightForWidth())
        self.resistL4.setSizePolicy(sizePolicy)
        self.resistL4.setDecimals(1)
        self.resistL4.setSingleStep(0.1)
        self.resistL4.setProperty("value", 30.0)
        self.resistL4.setObjectName(_fromUtf8("resistL4"))
        self.gridLayout_2.addWidget(self.resistL4, 5, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 6, 0, 1, 1)
        self.resistL5 = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resistL5.sizePolicy().hasHeightForWidth())
        self.resistL5.setSizePolicy(sizePolicy)
        self.resistL5.setDecimals(1)
        self.resistL5.setSingleStep(0.1)
        self.resistL5.setProperty("value", 30.0)
        self.resistL5.setObjectName(_fromUtf8("resistL5"))
        self.gridLayout_2.addWidget(self.resistL5, 6, 2, 1, 1)
        self.meanResisCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.meanResisCheckBox.setObjectName(_fromUtf8("meanResisCheckBox"))
        self.gridLayout_2.addWidget(self.meanResisCheckBox, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)
        self.saveButton = QtGui.QPushButton(AGTCalibrationDialog)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.gridLayout_3.addWidget(self.saveButton, 3, 1, 1, 1)
        self.cancelButton = QtGui.QPushButton(AGTCalibrationDialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout_3.addWidget(self.cancelButton, 3, 2, 1, 1)

        self.retranslateUi(AGTCalibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(AGTCalibrationDialog)

    def retranslateUi(self, AGTCalibrationDialog):
        AGTCalibrationDialog.setWindowTitle(_translate("AGTCalibrationDialog", "Calibration", None))
        self.label.setText(_translate("AGTCalibrationDialog", "EMI calibration file ", None))
        self.ButtonBrowse.setText(_translate("AGTCalibrationDialog", "browse", None))
        self.label_3.setText(_translate("AGTCalibrationDialog", "Altitude mesure bottom", None))
        self.label_4.setText(_translate("AGTCalibrationDialog", "Altitude mesure top", None))
        self.label_5.setText(_translate("AGTCalibrationDialog", "Electrical model", None))
        self.label_6.setText(_translate("AGTCalibrationDialog", "Thickness", None))
        self.label_7.setText(_translate("AGTCalibrationDialog", "Resistivity", None))
        self.label_9.setText(_translate("AGTCalibrationDialog", "Layer 1", None))
        self.label_10.setText(_translate("AGTCalibrationDialog", "Layer 2", None))
        self.label_11.setText(_translate("AGTCalibrationDialog", "Layer 3", None))
        self.label_12.setText(_translate("AGTCalibrationDialog", "Layer 4", None))
        self.label_13.setText(_translate("AGTCalibrationDialog", "Layer 5", None))
        self.meanResisCheckBox.setText(_translate("AGTCalibrationDialog", "Mean resistivity", None))
        self.saveButton.setText(_translate("AGTCalibrationDialog", "Save", None))
        self.cancelButton.setText(_translate("AGTCalibrationDialog", "Cancel", None))

