# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_electDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AGTElectDialogBase(object):
    def setupUi(self, AGTElectDialogBase):
        AGTElectDialogBase.setObjectName("AGTElectDialogBase")
        AGTElectDialogBase.resize(352, 458)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AGTElectDialogBase.sizePolicy().hasHeightForWidth())
        AGTElectDialogBase.setSizePolicy(sizePolicy)
        AGTElectDialogBase.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout_2 = QtWidgets.QGridLayout(AGTElectDialogBase)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(AGTElectDialogBase)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inFileLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.inFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.inFileLine.setObjectName("inFileLine")
        self.gridLayout.addWidget(self.inFileLine, 0, 1, 1, 1)
        self.ButtonBrowse = QtWidgets.QPushButton(self.groupBox_2)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName("ButtonBrowse")
        self.gridLayout.addWidget(self.ButtonBrowse, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gBox_Output = QtWidgets.QGroupBox(AGTElectDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_Output.sizePolicy().hasHeightForWidth())
        self.gBox_Output.setSizePolicy(sizePolicy)
        self.gBox_Output.setObjectName("gBox_Output")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gBox_Output)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.outputLabel = QtWidgets.QLabel(self.gBox_Output)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_3.addWidget(self.outputLabel, 0, 0, 1, 1)
        self.outputFilename = QtWidgets.QLineEdit(self.gBox_Output)
        self.outputFilename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputFilename.setObjectName("outputFilename")
        self.gridLayout_3.addWidget(self.outputFilename, 0, 1, 1, 1)
        self.datFilechkbox = QtWidgets.QCheckBox(self.gBox_Output)
        self.datFilechkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.datFilechkbox.setObjectName("datFilechkbox")
        self.gridLayout_3.addWidget(self.datFilechkbox, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gBox_Output, 1, 0, 1, 1)
        self.gBox_filter = QtWidgets.QGroupBox(AGTElectDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_filter.sizePolicy().hasHeightForWidth())
        self.gBox_filter.setSizePolicy(sizePolicy)
        self.gBox_filter.setTitle("")
        self.gBox_filter.setObjectName("gBox_filter")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gBox_filter)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_filt = QtWidgets.QCheckBox(self.gBox_filter)
        self.checkBox_filt.setObjectName("checkBox_filt")
        self.gridLayout_5.addWidget(self.checkBox_filt, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gBox_filter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.spinBox_mvp = QtWidgets.QSpinBox(self.gBox_filter)
        self.spinBox_mvp.setSuffix("")
        self.spinBox_mvp.setPrefix("")
        self.spinBox_mvp.setMaximum(100)
        self.spinBox_mvp.setProperty("value", 30)
        self.spinBox_mvp.setObjectName("spinBox_mvp")
        self.gridLayout_5.addWidget(self.spinBox_mvp, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gBox_filter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.spinBox_maskR = QtWidgets.QSpinBox(self.gBox_filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_maskR.sizePolicy().hasHeightForWidth())
        self.spinBox_maskR.setSizePolicy(sizePolicy)
        self.spinBox_maskR.setSuffix("")
        self.spinBox_maskR.setPrefix("")
        self.spinBox_maskR.setMinimum(3)
        self.spinBox_maskR.setMaximum(15)
        self.spinBox_maskR.setSingleStep(2)
        self.spinBox_maskR.setProperty("value", 3)
        self.spinBox_maskR.setObjectName("spinBox_maskR")
        self.gridLayout_5.addWidget(self.spinBox_maskR, 2, 1, 1, 1)
        self.checkBox_filt.raise_()
        self.label_4.raise_()
        self.spinBox_mvp.raise_()
        self.spinBox_maskR.raise_()
        self.label_5.raise_()
        self.gridLayout_2.addWidget(self.gBox_filter, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(AGTElectDialogBase)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_geo = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_geo.setEnabled(True)
        self.checkBox_geo.setObjectName("checkBox_geo")
        self.gridLayout_6.addWidget(self.checkBox_geo, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 3, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(AGTElectDialogBase)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 0, 0, 1, 1)
        self.allProcess_button = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allProcess_button.sizePolicy().hasHeightForWidth())
        self.allProcess_button.setSizePolicy(sizePolicy)
        self.allProcess_button.setObjectName("allProcess_button")
        self.gridLayout_4.addWidget(self.allProcess_button, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 4, 0, 1, 1)

        self.retranslateUi(AGTElectDialogBase)
        QtCore.QMetaObject.connectSlotsByName(AGTElectDialogBase)

    def retranslateUi(self, AGTElectDialogBase):
        _translate = QtCore.QCoreApplication.translate
        AGTElectDialogBase.setWindowTitle(_translate("AGTElectDialogBase", "RM15/RM85 processing"))
        self.label.setText(_translate("AGTElectDialogBase", "Raw data (.dat)"))
        self.ButtonBrowse.setText(_translate("AGTElectDialogBase", "browse"))
        self.gBox_Output.setTitle(_translate("AGTElectDialogBase", "Output files"))
        self.outputLabel.setText(_translate("AGTElectDialogBase", "Project name"))
        self.datFilechkbox.setText(_translate("AGTElectDialogBase", "Export also as .DAT"))
        self.checkBox_filt.setText(_translate("AGTElectDialogBase", "Median filter"))
        self.label_4.setText(_translate("AGTElectDialogBase", "Median value percentage %   "))
        self.label_5.setText(_translate("AGTElectDialogBase", "Kernel size      "))
        self.checkBox_geo.setText(_translate("AGTElectDialogBase", "Georeferencing"))
        self.allProcess_button.setText(_translate("AGTElectDialogBase", "run"))

