# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_EM31Dialog.ui'
#
# Created: Thu Apr 05 15:28:04 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AGTEM31Dialog(object):
    def setupUi(self, AGTEM31Dialog):
        AGTEM31Dialog.setObjectName(_fromUtf8("AGTEM31Dialog"))
        AGTEM31Dialog.resize(359, 448)
        self.gridLayout_3 = QtGui.QGridLayout(AGTEM31Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(AGTEM31Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_georefscr_3 = QtGui.QLabel(self.groupBox_3)
        self.label_georefscr_3.setObjectName(_fromUtf8("label_georefscr_3"))
        self.gridLayout.addWidget(self.label_georefscr_3, 2, 0, 1, 1)
        self.inFileLine = QtGui.QLineEdit(self.groupBox_3)
        self.inFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.inFileLine.setObjectName(_fromUtf8("inFileLine"))
        self.gridLayout.addWidget(self.inFileLine, 1, 1, 1, 1)
        self.ButtonBrowse = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowse.sizePolicy().hasHeightForWidth())
        self.ButtonBrowse.setSizePolicy(sizePolicy)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName(_fromUtf8("ButtonBrowse"))
        self.gridLayout.addWidget(self.ButtonBrowse, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.comboCRSImport = QtGui.QComboBox(self.groupBox_3)
        self.comboCRSImport.setObjectName(_fromUtf8("comboCRSImport"))
        self.gridLayout.addWidget(self.comboCRSImport, 2, 1, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gBox_Output = QtGui.QGroupBox(AGTEM31Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_Output.sizePolicy().hasHeightForWidth())
        self.gBox_Output.setSizePolicy(sizePolicy)
        self.gBox_Output.setObjectName(_fromUtf8("gBox_Output"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gBox_Output)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.outputLabel_2 = QtGui.QLabel(self.gBox_Output)
        self.outputLabel_2.setObjectName(_fromUtf8("outputLabel_2"))
        self.gridLayout_2.addWidget(self.outputLabel_2, 0, 0, 1, 1)
        self.label_georefscr_2 = QtGui.QLabel(self.gBox_Output)
        self.label_georefscr_2.setObjectName(_fromUtf8("label_georefscr_2"))
        self.gridLayout_2.addWidget(self.label_georefscr_2, 1, 0, 1, 2)
        self.datFilechkbox = QtGui.QCheckBox(self.gBox_Output)
        self.datFilechkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.datFilechkbox.setObjectName(_fromUtf8("datFilechkbox"))
        self.gridLayout_2.addWidget(self.datFilechkbox, 2, 0, 1, 4)
        self.coordFieldschk = QtGui.QCheckBox(self.gBox_Output)
        self.coordFieldschk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.coordFieldschk.setObjectName(_fromUtf8("coordFieldschk"))
        self.gridLayout_2.addWidget(self.coordFieldschk, 2, 4, 1, 2)
        self.ButtonBrowseShape = QtGui.QPushButton(self.gBox_Output)
        self.ButtonBrowseShape.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseShape.setObjectName(_fromUtf8("ButtonBrowseShape"))
        self.gridLayout_2.addWidget(self.ButtonBrowseShape, 0, 5, 1, 1)
        self.outputFilename = QtGui.QLineEdit(self.gBox_Output)
        self.outputFilename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputFilename.setObjectName(_fromUtf8("outputFilename"))
        self.gridLayout_2.addWidget(self.outputFilename, 0, 1, 1, 4)
        self.comboCRS = QtGui.QComboBox(self.gBox_Output)
        self.comboCRS.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCRS.sizePolicy().hasHeightForWidth())
        self.comboCRS.setSizePolicy(sizePolicy)
        self.comboCRS.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboCRS.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.comboCRS.setObjectName(_fromUtf8("comboCRS"))
        self.gridLayout_2.addWidget(self.comboCRS, 1, 3, 1, 3)
        self.gridLayout_3.addWidget(self.gBox_Output, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(AGTEM31Dialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.heightSpin = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightSpin.sizePolicy().hasHeightForWidth())
        self.heightSpin.setSizePolicy(sizePolicy)
        self.heightSpin.setDecimals(1)
        self.heightSpin.setSingleStep(0.1)
        self.heightSpin.setProperty("value", 0.7)
        self.heightSpin.setObjectName(_fromUtf8("heightSpin"))
        self.gridLayout_4.addWidget(self.heightSpin, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(AGTEM31Dialog)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.radioButtonHCP = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonHCP.setChecked(False)
        self.radioButtonHCP.setObjectName(_fromUtf8("radioButtonHCP"))
        self.gridLayout_5.addWidget(self.radioButtonHCP, 0, 1, 1, 1)
        self.radioButtonVCP = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonVCP.setChecked(True)
        self.radioButtonVCP.setObjectName(_fromUtf8("radioButtonVCP"))
        self.gridLayout_5.addWidget(self.radioButtonVCP, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.frame = QtGui.QFrame(AGTEM31Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.progressBar = QtGui.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_6.addWidget(self.progressBar, 0, 0, 1, 1)
        self.runButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.gridLayout_6.addWidget(self.runButton, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 4, 0, 1, 1)

        self.retranslateUi(AGTEM31Dialog)
        QtCore.QMetaObject.connectSlotsByName(AGTEM31Dialog)

    def retranslateUi(self, AGTEM31Dialog):
        AGTEM31Dialog.setWindowTitle(_translate("AGTEM31Dialog", "EM31 processing", None))
        self.groupBox_3.setTitle(_translate("AGTEM31Dialog", "Input file", None))
        self.label_georefscr_3.setText(_translate("AGTEM31Dialog", "Import CRS projection", None))
        self.ButtonBrowse.setText(_translate("AGTEM31Dialog", "browse", None))
        self.label.setText(_translate("AGTEM31Dialog", "Raw data (.dat)", None))
        self.gBox_Output.setTitle(_translate("AGTEM31Dialog", "Output files", None))
        self.outputLabel_2.setText(_translate("AGTEM31Dialog", "Shapefile", None))
        self.label_georefscr_2.setText(_translate("AGTEM31Dialog", "Export CRS projection", None))
        self.datFilechkbox.setText(_translate("AGTEM31Dialog", "Export also as .DAT", None))
        self.coordFieldschk.setText(_translate("AGTEM31Dialog", "Add coordinates fields", None))
        self.ButtonBrowseShape.setText(_translate("AGTEM31Dialog", "browse", None))
        self.label_3.setText(_translate("AGTEM31Dialog", "Sensor height (m)", None))
        self.label_4.setText(_translate("AGTEM31Dialog", "Coils geometry", None))
        self.radioButtonHCP.setText(_translate("AGTEM31Dialog", "HCP", None))
        self.radioButtonVCP.setText(_translate("AGTEM31Dialog", "VCP", None))
        self.runButton.setText(_translate("AGTEM31Dialog", "run", None))

