# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_ElecDownDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AGTElecDownDialog(object):
    def setupUi(self, AGTElecDownDialog):
        AGTElecDownDialog.setObjectName("AGTElecDownDialog")
        AGTElecDownDialog.resize(452, 494)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AGTElecDownDialog.sizePolicy().hasHeightForWidth())
        AGTElecDownDialog.setSizePolicy(sizePolicy)
        AGTElecDownDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(AGTElecDownDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.box = QtWidgets.QGroupBox(AGTElecDownDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box.sizePolicy().hasHeightForWidth())
        self.box.setSizePolicy(sizePolicy)
        self.box.setTitle("")
        self.box.setObjectName("box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineStepSpin = QtWidgets.QDoubleSpinBox(self.box)
        self.lineStepSpin.setSingleStep(0.1)
        self.lineStepSpin.setProperty("value", 1.0)
        self.lineStepSpin.setObjectName("lineStepSpin")
        self.gridLayout_2.addWidget(self.lineStepSpin, 11, 2, 1, 1)
        self.gridSizeSpinX = QtWidgets.QSpinBox(self.box)
        self.gridSizeSpinX.setProperty("value", 30)
        self.gridSizeSpinX.setObjectName("gridSizeSpinX")
        self.gridLayout_2.addWidget(self.gridSizeSpinX, 5, 2, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.box)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_2.addWidget(self.outputLabel, 0, 0, 1, 1)
        self.probeConfigCombo = QtWidgets.QComboBox(self.box)
        self.probeConfigCombo.setObjectName("probeConfigCombo")
        self.gridLayout_2.addWidget(self.probeConfigCombo, 12, 3, 1, 2)
        self.radioButton15 = QtWidgets.QRadioButton(self.box)
        self.radioButton15.setObjectName("radioButton15")
        self.gridLayout_2.addWidget(self.radioButton15, 2, 0, 1, 1)
        self.radioButton85 = QtWidgets.QRadioButton(self.box)
        self.radioButton85.setChecked(True)
        self.radioButton85.setObjectName("radioButton85")
        self.gridLayout_2.addWidget(self.radioButton85, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.box)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 1, 1, 1)
        self.outputLabel_2 = QtWidgets.QLabel(self.box)
        self.outputLabel_2.setObjectName("outputLabel_2")
        self.gridLayout_2.addWidget(self.outputLabel_2, 5, 1, 1, 1)
        self.outputFilename = QtWidgets.QLineEdit(self.box)
        self.outputFilename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputFilename.setObjectName("outputFilename")
        self.gridLayout_2.addWidget(self.outputFilename, 0, 1, 1, 2)
        self.ButtonBrowse = QtWidgets.QPushButton(self.box)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName("ButtonBrowse")
        self.gridLayout_2.addWidget(self.ButtonBrowse, 0, 4, 1, 1)
        self.nbGridSpin = QtWidgets.QSpinBox(self.box)
        self.nbGridSpin.setMinimum(1)
        self.nbGridSpin.setObjectName("nbGridSpin")
        self.gridLayout_2.addWidget(self.nbGridSpin, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.box)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 9, 1, 1, 2)
        self.nbChannelSpin = QtWidgets.QSpinBox(self.box)
        self.nbChannelSpin.setMinimum(1)
        self.nbChannelSpin.setProperty("value", 3)
        self.nbChannelSpin.setObjectName("nbChannelSpin")
        self.gridLayout_2.addWidget(self.nbChannelSpin, 7, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.box)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 12, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.box)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 11, 1, 1, 1)
        self.nbProbeSpin = QtWidgets.QSpinBox(self.box)
        self.nbProbeSpin.setMinimum(1)
        self.nbProbeSpin.setProperty("value", 4)
        self.nbProbeSpin.setObjectName("nbProbeSpin")
        self.gridLayout_2.addWidget(self.nbProbeSpin, 9, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.box)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.box)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 1, 1, 2)
        self.probeSpaceSpin = QtWidgets.QDoubleSpinBox(self.box)
        self.probeSpaceSpin.setSingleStep(0.1)
        self.probeSpaceSpin.setProperty("value", 0.5)
        self.probeSpaceSpin.setObjectName("probeSpaceSpin")
        self.gridLayout_2.addWidget(self.probeSpaceSpin, 6, 2, 1, 1)
        self.gridSizeSpinY = QtWidgets.QSpinBox(self.box)
        self.gridSizeSpinY.setProperty("value", 30)
        self.gridSizeSpinY.setObjectName("gridSizeSpinY")
        self.gridLayout_2.addWidget(self.gridSizeSpinY, 5, 4, 1, 1)
        self.outputLabel_3 = QtWidgets.QLabel(self.box)
        self.outputLabel_3.setObjectName("outputLabel_3")
        self.gridLayout_2.addWidget(self.outputLabel_3, 5, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.box)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 13, 1, 1, 2)
        self.currentIntSpin = QtWidgets.QDoubleSpinBox(self.box)
        self.currentIntSpin.setMaximum(200.0)
        self.currentIntSpin.setSingleStep(0.1)
        self.currentIntSpin.setProperty("value", 10.0)
        self.currentIntSpin.setObjectName("currentIntSpin")
        self.gridLayout_2.addWidget(self.currentIntSpin, 13, 3, 1, 1)
        self.collectedPtNbSpin = QtWidgets.QSpinBox(self.box)
        self.collectedPtNbSpin.setMinimum(6)
        self.collectedPtNbSpin.setObjectName("collectedPtNbSpin")
        self.gridLayout_2.addWidget(self.collectedPtNbSpin, 10, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.box)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 10, 1, 1, 1)
        self.gridLayout.addWidget(self.box, 0, 0, 1, 1)
        self.gBox_filter = QtWidgets.QGroupBox(AGTElecDownDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_filter.sizePolicy().hasHeightForWidth())
        self.gBox_filter.setSizePolicy(sizePolicy)
        self.gBox_filter.setTitle("")
        self.gBox_filter.setObjectName("gBox_filter")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gBox_filter)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.gBox_filter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.comCombo = QtWidgets.QComboBox(self.gBox_filter)
        self.comCombo.setObjectName("comCombo")
        self.gridLayout_3.addWidget(self.comCombo, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gBox_filter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 0, 1, 1)
        self.baudCombo = QtWidgets.QComboBox(self.gBox_filter)
        self.baudCombo.setObjectName("baudCombo")
        self.gridLayout_3.addWidget(self.baudCombo, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.gBox_filter, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(AGTElecDownDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.runButton = QtWidgets.QPushButton(self.widget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_3.addWidget(self.runButton)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)

        self.retranslateUi(AGTElecDownDialog)
        QtCore.QMetaObject.connectSlotsByName(AGTElecDownDialog)

    def retranslateUi(self, AGTElecDownDialog):
        _translate = QtCore.QCoreApplication.translate
        AGTElecDownDialog.setWindowTitle(_translate("AGTElecDownDialog", "RM15/RM85 download"))
        self.outputLabel.setText(_translate("AGTElecDownDialog", "Output file"))
        self.radioButton15.setText(_translate("AGTElecDownDialog", "RM15"))
        self.radioButton85.setText(_translate("AGTElecDownDialog", "RM85"))
        self.label.setText(_translate("AGTElecDownDialog", "Number of grids"))
        self.outputLabel_2.setText(_translate("AGTElecDownDialog", "Grid size (m)"))
        self.ButtonBrowse.setText(_translate("AGTElecDownDialog", "browse"))
        self.label_4.setText(_translate("AGTElecDownDialog", "Number of probes"))
        self.label_6.setText(_translate("AGTElecDownDialog", "Probe configuration"))
        self.label_5.setText(_translate("AGTElecDownDialog", "Line step (m)"))
        self.label_2.setText(_translate("AGTElecDownDialog", "Probe spacing (m)"))
        self.label_3.setText(_translate("AGTElecDownDialog", "Number of channels"))
        self.outputLabel_3.setText(_translate("AGTElecDownDialog", " X"))
        self.label_7.setText(_translate("AGTElecDownDialog", "Current intensity (mA)"))
        self.label_10.setText(_translate("AGTElecDownDialog", "Number of collected points/step"))
        self.label_8.setText(_translate("AGTElecDownDialog", "COM port"))
        self.label_9.setText(_translate("AGTElecDownDialog", "Baud rate"))
        self.runButton.setText(_translate("AGTElecDownDialog", "run"))

