# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_EM31Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AGTEM31Dialog(object):
    def setupUi(self, AGTEM31Dialog):
        AGTEM31Dialog.setObjectName("AGTEM31Dialog")
        AGTEM31Dialog.resize(351, 428)
        self.gridLayout_3 = QtWidgets.QGridLayout(AGTEM31Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(AGTEM31Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.heightSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightSpin.sizePolicy().hasHeightForWidth())
        self.heightSpin.setSizePolicy(sizePolicy)
        self.heightSpin.setDecimals(1)
        self.heightSpin.setSingleStep(0.1)
        self.heightSpin.setProperty("value", 0.7)
        self.heightSpin.setObjectName("heightSpin")
        self.gridLayout_4.addWidget(self.heightSpin, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(AGTEM31Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_georefscr_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_georefscr_3.setObjectName("label_georefscr_3")
        self.gridLayout.addWidget(self.label_georefscr_3, 2, 0, 1, 1)
        self.inFileLine = QtWidgets.QLineEdit(self.groupBox_3)
        self.inFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.inFileLine.setObjectName("inFileLine")
        self.gridLayout.addWidget(self.inFileLine, 1, 1, 1, 1)
        self.ButtonBrowse = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowse.sizePolicy().hasHeightForWidth())
        self.ButtonBrowse.setSizePolicy(sizePolicy)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName("ButtonBrowse")
        self.gridLayout.addWidget(self.ButtonBrowse, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.qgsProjectionSelectionImport = QgsProjectionSelectionWidget(self.groupBox_3)
        self.qgsProjectionSelectionImport.setObjectName("qgsProjectionSelectionImport")
        self.gridLayout.addWidget(self.qgsProjectionSelectionImport, 2, 1, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(AGTEM31Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_6.addWidget(self.progressBar, 0, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName("runButton")
        self.gridLayout_6.addWidget(self.runButton, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 4, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(AGTEM31Dialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.radioButtonHCP = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonHCP.setChecked(False)
        self.radioButtonHCP.setObjectName("radioButtonHCP")
        self.gridLayout_5.addWidget(self.radioButtonHCP, 0, 1, 1, 1)
        self.radioButtonVCP = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonVCP.setChecked(True)
        self.radioButtonVCP.setObjectName("radioButtonVCP")
        self.gridLayout_5.addWidget(self.radioButtonVCP, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.gBox_Output = QtWidgets.QGroupBox(AGTEM31Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_Output.sizePolicy().hasHeightForWidth())
        self.gBox_Output.setSizePolicy(sizePolicy)
        self.gBox_Output.setObjectName("gBox_Output")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gBox_Output)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outputLabel_2 = QtWidgets.QLabel(self.gBox_Output)
        self.outputLabel_2.setObjectName("outputLabel_2")
        self.gridLayout_2.addWidget(self.outputLabel_2, 0, 0, 1, 1)
        self.outputFilename = QtWidgets.QLineEdit(self.gBox_Output)
        self.outputFilename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputFilename.setObjectName("outputFilename")
        self.gridLayout_2.addWidget(self.outputFilename, 0, 1, 1, 1)
        self.ButtonBrowseShape = QtWidgets.QPushButton(self.gBox_Output)
        self.ButtonBrowseShape.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseShape.setObjectName("ButtonBrowseShape")
        self.gridLayout_2.addWidget(self.ButtonBrowseShape, 1, 1, 1, 1)
        self.label_georefscr_2 = QtWidgets.QLabel(self.gBox_Output)
        self.label_georefscr_2.setObjectName("label_georefscr_2")
        self.gridLayout_2.addWidget(self.label_georefscr_2, 2, 0, 1, 1)
        self.qgsProjectionSelectionExport = QgsProjectionSelectionWidget(self.gBox_Output)
        self.qgsProjectionSelectionExport.setObjectName("qgsProjectionSelectionExport")
        self.gridLayout_2.addWidget(self.qgsProjectionSelectionExport, 2, 1, 1, 1)
        self.datFilechkbox = QtWidgets.QCheckBox(self.gBox_Output)
        self.datFilechkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.datFilechkbox.setObjectName("datFilechkbox")
        self.gridLayout_2.addWidget(self.datFilechkbox, 3, 0, 1, 2)
        self.coordFieldschk = QtWidgets.QCheckBox(self.gBox_Output)
        self.coordFieldschk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.coordFieldschk.setObjectName("coordFieldschk")
        self.gridLayout_2.addWidget(self.coordFieldschk, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.gBox_Output, 1, 0, 1, 1)

        self.retranslateUi(AGTEM31Dialog)
        QtCore.QMetaObject.connectSlotsByName(AGTEM31Dialog)

    def retranslateUi(self, AGTEM31Dialog):
        _translate = QtCore.QCoreApplication.translate
        AGTEM31Dialog.setWindowTitle(_translate("AGTEM31Dialog", "EM31 processing"))
        self.label_3.setText(_translate("AGTEM31Dialog", "Sensor height (m)"))
        self.groupBox_3.setTitle(_translate("AGTEM31Dialog", "Input file"))
        self.label_georefscr_3.setText(_translate("AGTEM31Dialog", "Import CRS projection"))
        self.ButtonBrowse.setText(_translate("AGTEM31Dialog", "browse"))
        self.label.setText(_translate("AGTEM31Dialog", "Raw data (.dat)"))
        self.runButton.setText(_translate("AGTEM31Dialog", "run"))
        self.label_4.setText(_translate("AGTEM31Dialog", "Coils geometry"))
        self.radioButtonHCP.setText(_translate("AGTEM31Dialog", "HCP"))
        self.radioButtonVCP.setText(_translate("AGTEM31Dialog", "VCP"))
        self.gBox_Output.setTitle(_translate("AGTEM31Dialog", "Output files"))
        self.outputLabel_2.setText(_translate("AGTEM31Dialog", "Shapefile"))
        self.ButtonBrowseShape.setText(_translate("AGTEM31Dialog", "browse"))
        self.label_georefscr_2.setText(_translate("AGTEM31Dialog", "Export CRS projection"))
        self.datFilechkbox.setText(_translate("AGTEM31Dialog", "Export also as .DAT"))
        self.coordFieldschk.setText(_translate("AGTEM31Dialog", "Add coordinates fields"))
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
