# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_georefDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AGTGeorefDialog(object):
    def setupUi(self, AGTGeorefDialog):
        AGTGeorefDialog.setObjectName("AGTGeorefDialog")
        AGTGeorefDialog.resize(501, 299)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AGTGeorefDialog.sizePolicy().hasHeightForWidth())
        AGTGeorefDialog.setSizePolicy(sizePolicy)
        AGTGeorefDialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(AGTGeorefDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLabel = QtWidgets.QLabel(AGTGeorefDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gridLabel.setFont(font)
        self.gridLabel.setText("")
        self.gridLabel.setObjectName("gridLabel")
        self.gridLayout.addWidget(self.gridLabel, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(AGTGeorefDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mouseclickPointMap2 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouseclickPointMap2.sizePolicy().hasHeightForWidth())
        self.mouseclickPointMap2.setSizePolicy(sizePolicy)
        self.mouseclickPointMap2.setCheckable(True)
        self.mouseclickPointMap2.setObjectName("mouseclickPointMap2")
        self.gridLayout_3.addWidget(self.mouseclickPointMap2, 1, 4, 1, 1)
        self.x2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.x2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.x2.setInputMask("")
        self.x2.setText("")
        self.x2.setObjectName("x2")
        self.gridLayout_3.addWidget(self.x2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.xt2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xt2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.xt2.setObjectName("xt2")
        self.gridLayout_3.addWidget(self.xt2, 0, 3, 1, 1)
        self.yt2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.yt2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.yt2.setObjectName("yt2")
        self.gridLayout_3.addWidget(self.yt2, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.y2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.y2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.y2.setObjectName("y2")
        self.gridLayout_3.addWidget(self.y2, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(AGTGeorefDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.x1 = QtWidgets.QLineEdit(self.groupBox)
        self.x1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.x1.setInputMask("")
        self.x1.setText("")
        self.x1.setObjectName("x1")
        self.gridLayout_2.addWidget(self.x1, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.xt1 = QtWidgets.QLineEdit(self.groupBox)
        self.xt1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.xt1.setObjectName("xt1")
        self.gridLayout_2.addWidget(self.xt1, 0, 3, 1, 1)
        self.mouseclickPointMap1 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouseclickPointMap1.sizePolicy().hasHeightForWidth())
        self.mouseclickPointMap1.setSizePolicy(sizePolicy)
        self.mouseclickPointMap1.setCheckable(True)
        self.mouseclickPointMap1.setDefault(False)
        self.mouseclickPointMap1.setFlat(False)
        self.mouseclickPointMap1.setObjectName("mouseclickPointMap1")
        self.gridLayout_2.addWidget(self.mouseclickPointMap1, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.y1 = QtWidgets.QLineEdit(self.groupBox)
        self.y1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.y1.setObjectName("y1")
        self.gridLayout_2.addWidget(self.y1, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 2, 1, 1)
        self.yt1 = QtWidgets.QLineEdit(self.groupBox)
        self.yt1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.yt1.setObjectName("yt1")
        self.gridLayout_2.addWidget(self.yt1, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)
        self.widget = QtWidgets.QWidget(AGTGeorefDialog)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.runButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName("runButton")
        self.gridLayout_4.addWidget(self.runButton, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 2, 1, 1, 1)

        self.retranslateUi(AGTGeorefDialog)
        self.buttonBox.rejected.connect(AGTGeorefDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AGTGeorefDialog)

    def retranslateUi(self, AGTGeorefDialog):
        _translate = QtCore.QCoreApplication.translate
        AGTGeorefDialog.setWindowTitle(_translate("AGTGeorefDialog", "Georeferencing"))
        self.groupBox_2.setTitle(_translate("AGTGeorefDialog", "Point 2"))
        self.mouseclickPointMap2.setText(_translate("AGTGeorefDialog", "Select point on the map"))
        self.label_7.setText(_translate("AGTGeorefDialog", "to"))
        self.label_5.setText(_translate("AGTGeorefDialog", "x"))
        self.label_6.setText(_translate("AGTGeorefDialog", "y"))
        self.label_8.setText(_translate("AGTGeorefDialog", "to"))
        self.groupBox.setTitle(_translate("AGTGeorefDialog", "Point 1"))
        self.label.setText(_translate("AGTGeorefDialog", "x"))
        self.label_3.setText(_translate("AGTGeorefDialog", "to"))
        self.mouseclickPointMap1.setText(_translate("AGTGeorefDialog", "Select point on the map"))
        self.label_2.setText(_translate("AGTGeorefDialog", "y"))
        self.label_4.setText(_translate("AGTGeorefDialog", "to"))
        self.runButton.setText(_translate("AGTGeorefDialog", "run"))

