# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_georefDialog.ui'
#
# Created: Wed Apr 11 10:28:20 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AGTGeorefDialog(object):
    def setupUi(self, AGTGeorefDialog):
        AGTGeorefDialog.setObjectName(_fromUtf8("AGTGeorefDialog"))
        AGTGeorefDialog.resize(501, 299)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AGTGeorefDialog.sizePolicy().hasHeightForWidth())
        AGTGeorefDialog.setSizePolicy(sizePolicy)
        AGTGeorefDialog.setSizeGripEnabled(False)
        self.gridLayout = QtGui.QGridLayout(AGTGeorefDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLabel = QtGui.QLabel(AGTGeorefDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gridLabel.setFont(font)
        self.gridLabel.setText(_fromUtf8(""))
        self.gridLabel.setObjectName(_fromUtf8("gridLabel"))
        self.gridLayout.addWidget(self.gridLabel, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(AGTGeorefDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mouseclickPointMap2 = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouseclickPointMap2.sizePolicy().hasHeightForWidth())
        self.mouseclickPointMap2.setSizePolicy(sizePolicy)
        self.mouseclickPointMap2.setCheckable(True)
        self.mouseclickPointMap2.setObjectName(_fromUtf8("mouseclickPointMap2"))
        self.gridLayout_3.addWidget(self.mouseclickPointMap2, 1, 4, 1, 1)
        self.x2 = QtGui.QLineEdit(self.groupBox_2)
        self.x2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.x2.setInputMask(_fromUtf8(""))
        self.x2.setText(_fromUtf8(""))
        self.x2.setObjectName(_fromUtf8("x2"))
        self.gridLayout_3.addWidget(self.x2, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.xt2 = QtGui.QLineEdit(self.groupBox_2)
        self.xt2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.xt2.setObjectName(_fromUtf8("xt2"))
        self.gridLayout_3.addWidget(self.xt2, 0, 3, 1, 1)
        self.yt2 = QtGui.QLineEdit(self.groupBox_2)
        self.yt2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.yt2.setObjectName(_fromUtf8("yt2"))
        self.gridLayout_3.addWidget(self.yt2, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.y2 = QtGui.QLineEdit(self.groupBox_2)
        self.y2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.y2.setObjectName(_fromUtf8("y2"))
        self.gridLayout_3.addWidget(self.y2, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(AGTGeorefDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.x1 = QtGui.QLineEdit(self.groupBox)
        self.x1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.x1.setInputMask(_fromUtf8(""))
        self.x1.setText(_fromUtf8(""))
        self.x1.setObjectName(_fromUtf8("x1"))
        self.gridLayout_2.addWidget(self.x1, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.xt1 = QtGui.QLineEdit(self.groupBox)
        self.xt1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.xt1.setObjectName(_fromUtf8("xt1"))
        self.gridLayout_2.addWidget(self.xt1, 0, 3, 1, 1)
        self.mouseclickPointMap1 = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouseclickPointMap1.sizePolicy().hasHeightForWidth())
        self.mouseclickPointMap1.setSizePolicy(sizePolicy)
        self.mouseclickPointMap1.setCheckable(True)
        self.mouseclickPointMap1.setDefault(False)
        self.mouseclickPointMap1.setFlat(False)
        self.mouseclickPointMap1.setObjectName(_fromUtf8("mouseclickPointMap1"))
        self.gridLayout_2.addWidget(self.mouseclickPointMap1, 1, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.y1 = QtGui.QLineEdit(self.groupBox)
        self.y1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.y1.setObjectName(_fromUtf8("y1"))
        self.gridLayout_2.addWidget(self.y1, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 2, 1, 1)
        self.yt1 = QtGui.QLineEdit(self.groupBox)
        self.yt1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.yt1.setObjectName(_fromUtf8("yt1"))
        self.gridLayout_2.addWidget(self.yt1, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)
        self.widget = QtGui.QWidget(AGTGeorefDialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.runButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.gridLayout_4.addWidget(self.runButton, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 2, 1, 1, 1)

        self.retranslateUi(AGTGeorefDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), AGTGeorefDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AGTGeorefDialog)

    def retranslateUi(self, AGTGeorefDialog):
        AGTGeorefDialog.setWindowTitle(_translate("AGTGeorefDialog", "Georeferencing", None))
        self.groupBox_2.setTitle(_translate("AGTGeorefDialog", "Point 2", None))
        self.mouseclickPointMap2.setText(_translate("AGTGeorefDialog", "Select point on the map", None))
        self.label_7.setText(_translate("AGTGeorefDialog", "to", None))
        self.label_5.setText(_translate("AGTGeorefDialog", "x", None))
        self.label_6.setText(_translate("AGTGeorefDialog", "y", None))
        self.label_8.setText(_translate("AGTGeorefDialog", "to", None))
        self.groupBox.setTitle(_translate("AGTGeorefDialog", "Point 1", None))
        self.label.setText(_translate("AGTGeorefDialog", "x", None))
        self.label_3.setText(_translate("AGTGeorefDialog", "to", None))
        self.mouseclickPointMap1.setText(_translate("AGTGeorefDialog", "Select point on the map", None))
        self.label_2.setText(_translate("AGTGeorefDialog", "y", None))
        self.label_4.setText(_translate("AGTGeorefDialog", "to", None))
        self.runButton.setText(_translate("AGTGeorefDialog", "run", None))

