# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_InterpolateurDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InterpolatorDialog(object):
    def setupUi(self, InterpolatorDialog):
        InterpolatorDialog.setObjectName("InterpolatorDialog")
        InterpolatorDialog.resize(446, 532)
        self.gridLayout_5 = QtWidgets.QGridLayout(InterpolatorDialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(InterpolatorDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.VectorComboBox = QtWidgets.QComboBox(self.groupBox)
        self.VectorComboBox.setObjectName("VectorComboBox")
        self.gridLayout.addWidget(self.VectorComboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.FieldsComboBox = QtWidgets.QComboBox(self.groupBox)
        self.FieldsComboBox.setObjectName("FieldsComboBox")
        self.gridLayout.addWidget(self.FieldsComboBox, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 2)
        self.Methode = QtWidgets.QGroupBox(InterpolatorDialog)
        self.Methode.setObjectName("Methode")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Methode)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Electromagnetic = QtWidgets.QRadioButton(self.Methode)
        self.Electromagnetic.setChecked(True)
        self.Electromagnetic.setObjectName("Electromagnetic")
        self.gridLayout_2.addWidget(self.Electromagnetic, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Methode)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.Magnetic = QtWidgets.QRadioButton(self.Methode)
        self.Magnetic.setObjectName("Magnetic")
        self.gridLayout_2.addWidget(self.Magnetic, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Methode)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.Electric = QtWidgets.QRadioButton(self.Methode)
        self.Electric.setObjectName("Electric")
        self.gridLayout_2.addWidget(self.Electric, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Methode)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.gridLayout_5.addWidget(self.Methode, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(InterpolatorDialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.kernel = QtWidgets.QLabel(self.groupBox_2)
        self.kernel.setObjectName("kernel")
        self.gridLayout_3.addWidget(self.kernel, 0, 0, 1, 1)
        self.doubleSpinBox_window = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_window.setDecimals(2)
        self.doubleSpinBox_window.setMaximum(10000.0)
        self.doubleSpinBox_window.setProperty("value", 1.5)
        self.doubleSpinBox_window.setObjectName("doubleSpinBox_window")
        self.gridLayout_3.addWidget(self.doubleSpinBox_window, 0, 1, 1, 1)
        self.kernel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.kernel_2.setObjectName("kernel_2")
        self.gridLayout_3.addWidget(self.kernel_2, 1, 0, 1, 1)
        self.doubleSpinBox_pixelsize = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_pixelsize.setDecimals(2)
        self.doubleSpinBox_pixelsize.setMaximum(10000.0)
        self.doubleSpinBox_pixelsize.setProperty("value", 0.5)
        self.doubleSpinBox_pixelsize.setObjectName("doubleSpinBox_pixelsize")
        self.gridLayout_3.addWidget(self.doubleSpinBox_pixelsize, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(InterpolatorDialog)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.outputLabel = QtWidgets.QLabel(self.groupBox_3)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_4.addWidget(self.outputLabel, 0, 0, 1, 1)
        self.outputFilename = QtWidgets.QLineEdit(self.groupBox_3)
        self.outputFilename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputFilename.setObjectName("outputFilename")
        self.gridLayout_4.addWidget(self.outputFilename, 0, 1, 1, 1)
        self.ButtonBrowseRaster = QtWidgets.QPushButton(self.groupBox_3)
        self.ButtonBrowseRaster.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseRaster.setObjectName("ButtonBrowseRaster")
        self.gridLayout_4.addWidget(self.ButtonBrowseRaster, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 3, 0, 1, 2)
        self.runButton = QtWidgets.QPushButton(InterpolatorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.runButton.setObjectName("runButton")
        self.gridLayout_5.addWidget(self.runButton, 4, 1, 1, 1)

        self.retranslateUi(InterpolatorDialog)
        self.VectorComboBox.editTextChanged['QString'].connect(self.VectorComboBox.setEditText)
        QtCore.QMetaObject.connectSlotsByName(InterpolatorDialog)

    def retranslateUi(self, InterpolatorDialog):
        _translate = QtCore.QCoreApplication.translate
        InterpolatorDialog.setWindowTitle(_translate("InterpolatorDialog", "Interpolator Dialog"))
        self.label.setText(_translate("InterpolatorDialog", "Points layer"))
        self.label_2.setText(_translate("InterpolatorDialog", "Attribut"))
        self.Methode.setTitle(_translate("InterpolatorDialog", "Method"))
        self.Electromagnetic.setText(_translate("InterpolatorDialog", "Electromagnetic"))
        self.label_3.setText(_translate("InterpolatorDialog", "Recall cubic spline from SAGA tools"))
        self.Magnetic.setText(_translate("InterpolatorDialog", "Magnetic"))
        self.label_4.setText(_translate("InterpolatorDialog", "Recall inverse distance weighted  from SAGA tools"))
        self.Electric.setText(_translate("InterpolatorDialog", "Electrical"))
        self.label_5.setText(_translate("InterpolatorDialog", "Recall Multi-level B spline from SAGA tools"))
        self.kernel.setText(_translate("InterpolatorDialog", "Searching windows"))
        self.kernel_2.setText(_translate("InterpolatorDialog", "Pixel size"))
        self.outputLabel.setText(_translate("InterpolatorDialog", " Raster output"))
        self.ButtonBrowseRaster.setText(_translate("InterpolatorDialog", "browse"))
        self.runButton.setText(_translate("InterpolatorDialog", "run"))
