# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_MultiFreqDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AGTMultiFreqDialog(object):
    def setupUi(self, AGTMultiFreqDialog):
        AGTMultiFreqDialog.setObjectName("AGTMultiFreqDialog")
        AGTMultiFreqDialog.resize(515, 788)
        self.gridLayout_14 = QtWidgets.QGridLayout(AGTMultiFreqDialog)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_2 = QtWidgets.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.radioButtonHCP = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonHCP.setChecked(True)
        self.radioButtonHCP.setObjectName("radioButtonHCP")
        self.gridLayout_6.addWidget(self.radioButtonHCP, 0, 1, 1, 1)
        self.radioButtonVCP = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonVCP.setObjectName("radioButtonVCP")
        self.gridLayout_6.addWidget(self.radioButtonVCP, 0, 2, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_2, 8, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 2, 1, 1)
        self.gnssXShift = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gnssXShift.sizePolicy().hasHeightForWidth())
        self.gnssXShift.setSizePolicy(sizePolicy)
        self.gnssXShift.setDecimals(2)
        self.gnssXShift.setMinimum(-200.0)
        self.gnssXShift.setSingleStep(0.1)
        self.gnssXShift.setProperty("value", -0.2)
        self.gnssXShift.setObjectName("gnssXShift")
        self.gridLayout_7.addWidget(self.gnssXShift, 0, 3, 1, 1)
        self.gnssYShift = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.gnssYShift.setMinimum(-99.0)
        self.gnssYShift.setSingleStep(0.1)
        self.gnssYShift.setProperty("value", -0.4)
        self.gnssYShift.setObjectName("gnssYShift")
        self.gridLayout_7.addWidget(self.gnssYShift, 0, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.calibButton = QtWidgets.QPushButton(self.groupBox_5)
        self.calibButton.setObjectName("calibButton")
        self.gridLayout.addWidget(self.calibButton, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.magSusceptChkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.magSusceptChkBox.setObjectName("magSusceptChkBox")
        self.gridLayout.addWidget(self.magSusceptChkBox, 2, 0, 1, 3)
        self.CalibrationChkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.CalibrationChkBox.setObjectName("CalibrationChkBox")
        self.gridLayout.addWidget(self.CalibrationChkBox, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        self.elecConductChkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.elecConductChkBox.setObjectName("elecConductChkBox")
        self.gridLayout.addWidget(self.elecConductChkBox, 1, 0, 1, 3)
        self.conductCorrectChkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.conductCorrectChkBox.setEnabled(False)
        self.conductCorrectChkBox.setObjectName("conductCorrectChkBox")
        self.gridLayout.addWidget(self.conductCorrectChkBox, 3, 2, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(77, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_5, 13, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(AGTMultiFreqDialog)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ButtonBrowseData = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowseData.sizePolicy().hasHeightForWidth())
        self.ButtonBrowseData.setSizePolicy(sizePolicy)
        self.ButtonBrowseData.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseData.setObjectName("ButtonBrowseData")
        self.gridLayout_2.addWidget(self.ButtonBrowseData, 0, 2, 1, 1)
        self.dataInFileLine = QtWidgets.QLineEdit(self.widget_2)
        self.dataInFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dataInFileLine.setObjectName("dataInFileLine")
        self.gridLayout_2.addWidget(self.dataInFileLine, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.widget_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(AGTMultiFreqDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(324, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 1, 1, 1)
        self.altSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altSpin.sizePolicy().hasHeightForWidth())
        self.altSpin.setSizePolicy(sizePolicy)
        self.altSpin.setDecimals(1)
        self.altSpin.setSingleStep(0.1)
        self.altSpin.setProperty("value", 0.3)
        self.altSpin.setObjectName("altSpin")
        self.gridLayout_5.addWidget(self.altSpin, 0, 2, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox, 7, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(AGTMultiFreqDialog)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.progressBar = QtWidgets.QProgressBar(self.widget_4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_10.addWidget(self.progressBar, 0, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName("runButton")
        self.gridLayout_10.addWidget(self.runButton, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.widget_4, 16, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(AGTMultiFreqDialog)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gnssInFileLine = QtWidgets.QLineEdit(self.widget_3)
        self.gnssInFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gnssInFileLine.setObjectName("gnssInFileLine")
        self.gridLayout_3.addWidget(self.gnssInFileLine, 0, 1, 1, 7)
        self.ButtonBrowseGnss = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowseGnss.sizePolicy().hasHeightForWidth())
        self.ButtonBrowseGnss.setSizePolicy(sizePolicy)
        self.ButtonBrowseGnss.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseGnss.setObjectName("ButtonBrowseGnss")
        self.gridLayout_3.addWidget(self.ButtonBrowseGnss, 0, 8, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 6, 1, 1)
        self.gnssHourShift = QtWidgets.QSpinBox(self.widget_3)
        self.gnssHourShift.setMinimum(-99999)
        self.gnssHourShift.setMaximum(99999)
        self.gnssHourShift.setObjectName("gnssHourShift")
        self.gridLayout_3.addWidget(self.gnssHourShift, 2, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.gnssSecondsShift = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.gnssSecondsShift.setMinimum(-60.0)
        self.gnssSecondsShift.setMaximum(60.0)
        self.gnssSecondsShift.setObjectName("gnssSecondsShift")
        self.gridLayout_3.addWidget(self.gnssSecondsShift, 2, 7, 1, 1)
        self.gnssMinuteShift = QtWidgets.QSpinBox(self.widget_3)
        self.gnssMinuteShift.setMinimum(-60)
        self.gnssMinuteShift.setMaximum(60)
        self.gnssMinuteShift.setObjectName("gnssMinuteShift")
        self.gridLayout_3.addWidget(self.gnssMinuteShift, 2, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 2, 1, 1)
        self.gridLayout_14.addWidget(self.widget_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.quadChkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.quadChkBox.setObjectName("quadChkBox")
        self.gridLayout_8.addWidget(self.quadChkBox, 1, 0, 1, 1)
        self.inphaseChkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.inphaseChkBox.setObjectName("inphaseChkBox")
        self.gridLayout_8.addWidget(self.inphaseChkBox, 1, 1, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_4, 5, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(AGTMultiFreqDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.decimChkBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.decimChkBox.setObjectName("decimChkBox")
        self.gridLayout_11.addWidget(self.decimChkBox, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 1, 1, 1, 1)
        self.decimSpin = QtWidgets.QSpinBox(self.groupBox_6)
        self.decimSpin.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decimSpin.sizePolicy().hasHeightForWidth())
        self.decimSpin.setSizePolicy(sizePolicy)
        self.decimSpin.setSuffix("")
        self.decimSpin.setPrefix("1/")
        self.decimSpin.setMinimum(1)
        self.decimSpin.setMaximum(100)
        self.decimSpin.setProperty("value", 5)
        self.decimSpin.setObjectName("decimSpin")
        self.gridLayout_11.addWidget(self.decimSpin, 1, 2, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem7 = QtWidgets.QSpacerItem(186, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem7, 0, 1, 1, 1)
        self.windowSizeSpinIp = QtWidgets.QSpinBox(self.groupBox_9)
        self.windowSizeSpinIp.setEnabled(False)
        self.windowSizeSpinIp.setMaximum(500)
        self.windowSizeSpinIp.setProperty("value", 5)
        self.windowSizeSpinIp.setObjectName("windowSizeSpinIp")
        self.gridLayout_13.addWidget(self.windowSizeSpinIp, 0, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setEnabled(False)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 0, 5, 1, 1)
        self.windowSlideMeanIp = QtWidgets.QRadioButton(self.groupBox_9)
        self.windowSlideMeanIp.setEnabled(False)
        self.windowSlideMeanIp.setObjectName("windowSlideMeanIp")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(AGTMultiFreqDialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.windowSlideMeanIp)
        self.gridLayout_13.addWidget(self.windowSlideMeanIp, 0, 3, 1, 1)
        self.windowSlideMedianIp = QtWidgets.QRadioButton(self.groupBox_9)
        self.windowSlideMedianIp.setEnabled(False)
        self.windowSlideMedianIp.setCheckable(True)
        self.windowSlideMedianIp.setChecked(True)
        self.windowSlideMedianIp.setObjectName("windowSlideMedianIp")
        self.buttonGroup_2.addButton(self.windowSlideMedianIp)
        self.gridLayout_13.addWidget(self.windowSlideMedianIp, 0, 2, 1, 1)
        self.SlidingWindowChkBoxIp = QtWidgets.QCheckBox(self.groupBox_9)
        self.SlidingWindowChkBoxIp.setObjectName("SlidingWindowChkBoxIp")
        self.gridLayout_13.addWidget(self.SlidingWindowChkBoxIp, 0, 0, 1, 1)
        self.SlidingWindowChkBoxQ = QtWidgets.QCheckBox(self.groupBox_9)
        self.SlidingWindowChkBoxQ.setChecked(False)
        self.SlidingWindowChkBoxQ.setTristate(False)
        self.SlidingWindowChkBoxQ.setObjectName("SlidingWindowChkBoxQ")
        self.gridLayout_13.addWidget(self.SlidingWindowChkBoxQ, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(436, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem8, 1, 1, 1, 1)
        self.windowSlideMedianQ = QtWidgets.QRadioButton(self.groupBox_9)
        self.windowSlideMedianQ.setEnabled(False)
        self.windowSlideMedianQ.setCheckable(True)
        self.windowSlideMedianQ.setChecked(True)
        self.windowSlideMedianQ.setObjectName("windowSlideMedianQ")
        self.buttonGroup = QtWidgets.QButtonGroup(AGTMultiFreqDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.windowSlideMedianQ)
        self.gridLayout_13.addWidget(self.windowSlideMedianQ, 1, 2, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton.setEnabled(False)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout_13.addWidget(self.radioButton, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setEnabled(False)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 1, 5, 1, 1)
        self.windowSizeSpinQ = QtWidgets.QSpinBox(self.groupBox_9)
        self.windowSizeSpinQ.setEnabled(False)
        self.windowSizeSpinQ.setMaximum(500)
        self.windowSizeSpinQ.setProperty("value", 5)
        self.windowSizeSpinQ.setObjectName("windowSizeSpinQ")
        self.gridLayout_13.addWidget(self.windowSizeSpinQ, 1, 6, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_9, 6, 0, 1, 1)
        self.gBox_Output = QtWidgets.QGroupBox(AGTMultiFreqDialog)
        self.gBox_Output.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_Output.sizePolicy().hasHeightForWidth())
        self.gBox_Output.setSizePolicy(sizePolicy)
        self.gBox_Output.setObjectName("gBox_Output")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gBox_Output)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ButtonBrowseShape = QtWidgets.QPushButton(self.gBox_Output)
        self.ButtonBrowseShape.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseShape.setObjectName("ButtonBrowseShape")
        self.gridLayout_12.addWidget(self.ButtonBrowseShape, 0, 2, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.gBox_Output)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout_12.addWidget(self.outputLabel, 0, 0, 1, 1)
        self.outputFilename = QtWidgets.QLineEdit(self.gBox_Output)
        self.outputFilename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputFilename.setObjectName("outputFilename")
        self.gridLayout_12.addWidget(self.outputFilename, 0, 1, 1, 1)
        self.label_georefscr = QtWidgets.QLabel(self.gBox_Output)
        self.label_georefscr.setObjectName("label_georefscr")
        self.gridLayout_12.addWidget(self.label_georefscr, 2, 0, 1, 1)
        self.qgsProjectionSelectionExport = QgsProjectionSelectionWidget(self.gBox_Output)
        self.qgsProjectionSelectionExport.setObjectName("qgsProjectionSelectionExport")
        self.gridLayout_12.addWidget(self.qgsProjectionSelectionExport, 2, 1, 1, 2)
        self.gridLayout_14.addWidget(self.gBox_Output, 15, 0, 1, 1)
        self.frame = QtWidgets.QFrame(AGTMultiFreqDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label_georefscr_2 = QtWidgets.QLabel(self.frame)
        self.label_georefscr_2.setObjectName("label_georefscr_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_georefscr_2)
        self.qgsProjectionSelectionImport = QgsProjectionSelectionWidget(self.frame)
        self.qgsProjectionSelectionImport.setObjectName("qgsProjectionSelectionImport")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.qgsProjectionSelectionImport)
        self.gridLayout_14.addWidget(self.frame, 2, 0, 1, 1)

        self.retranslateUi(AGTMultiFreqDialog)
        self.SlidingWindowChkBoxQ.toggled['bool'].connect(self.windowSlideMedianQ.setEnabled)
        self.SlidingWindowChkBoxQ.toggled['bool'].connect(self.windowSizeSpinQ.setEnabled)
        self.SlidingWindowChkBoxQ.toggled['bool'].connect(self.radioButton.setEnabled)
        self.SlidingWindowChkBoxQ.toggled['bool'].connect(self.label_12.setEnabled)
        self.SlidingWindowChkBoxIp.toggled['bool'].connect(self.windowSlideMedianIp.setEnabled)
        self.SlidingWindowChkBoxIp.toggled['bool'].connect(self.windowSlideMeanIp.setEnabled)
        self.SlidingWindowChkBoxIp.toggled['bool'].connect(self.label_13.setEnabled)
        self.SlidingWindowChkBoxIp.toggled['bool'].connect(self.windowSizeSpinIp.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(AGTMultiFreqDialog)

    def retranslateUi(self, AGTMultiFreqDialog):
        _translate = QtCore.QCoreApplication.translate
        AGTMultiFreqDialog.setWindowTitle(_translate("AGTMultiFreqDialog", "GEM2 / EMP400"))
        self.label_4.setText(_translate("AGTMultiFreqDialog", "Coils geometry"))
        self.radioButtonHCP.setText(_translate("AGTMultiFreqDialog", "HCP (vertical dipole)"))
        self.radioButtonVCP.setText(_translate("AGTMultiFreqDialog", "VCP (horizontal dipole)"))
        self.label_5.setText(_translate("AGTMultiFreqDialog", "Spatial shift/GNSS"))
        self.label_6.setText(_translate("AGTMultiFreqDialog", "X"))
        self.label_7.setText(_translate("AGTMultiFreqDialog", "Y"))
        self.groupBox_5.setTitle(_translate("AGTMultiFreqDialog", "Physical parameters computation"))
        self.calibButton.setText(_translate("AGTMultiFreqDialog", "Calibration parameters"))
        self.magSusceptChkBox.setText(_translate("AGTMultiFreqDialog", "Magnetic susceptibility"))
        self.CalibrationChkBox.setText(_translate("AGTMultiFreqDialog", "Calibration"))
        self.elecConductChkBox.setText(_translate("AGTMultiFreqDialog", "Electrical conductivity"))
        self.conductCorrectChkBox.setText(_translate("AGTMultiFreqDialog", "Conductivity correction of In Phase"))
        self.ButtonBrowseData.setText(_translate("AGTMultiFreqDialog", "browse"))
        self.label.setText(_translate("AGTMultiFreqDialog", "Raw data"))
        self.label_3.setText(_translate("AGTMultiFreqDialog", "Device height (m)"))
        self.runButton.setText(_translate("AGTMultiFreqDialog", "run"))
        self.label_2.setText(_translate("AGTMultiFreqDialog", "GNSS data (.dat)"))
        self.ButtonBrowseGnss.setText(_translate("AGTMultiFreqDialog", "browse"))
        self.label_11.setText(_translate("AGTMultiFreqDialog", "Seconds:"))
        self.label_10.setText(_translate("AGTMultiFreqDialog", "Minutes:"))
        self.label_8.setText(_translate("AGTMultiFreqDialog", "GNSS Time Shift"))
        self.label_9.setText(_translate("AGTMultiFreqDialog", "Hours:"))
        self.groupBox_4.setTitle(_translate("AGTMultiFreqDialog", "Median removal (by profile)"))
        self.quadChkBox.setText(_translate("AGTMultiFreqDialog", "Quadrature"))
        self.inphaseChkBox.setText(_translate("AGTMultiFreqDialog", "In-phase"))
        self.groupBox_6.setTitle(_translate("AGTMultiFreqDialog", "Decimation"))
        self.decimChkBox.setText(_translate("AGTMultiFreqDialog", "Decimation"))
        self.groupBox_9.setTitle(_translate("AGTMultiFreqDialog", "Sliding Window"))
        self.label_13.setText(_translate("AGTMultiFreqDialog", "Window size"))
        self.windowSlideMeanIp.setText(_translate("AGTMultiFreqDialog", "Mean"))
        self.windowSlideMedianIp.setText(_translate("AGTMultiFreqDialog", "Median"))
        self.SlidingWindowChkBoxIp.setText(_translate("AGTMultiFreqDialog", "In-phase filtering"))
        self.SlidingWindowChkBoxQ.setText(_translate("AGTMultiFreqDialog", "Quadrature filtering"))
        self.windowSlideMedianQ.setText(_translate("AGTMultiFreqDialog", "Median"))
        self.radioButton.setText(_translate("AGTMultiFreqDialog", "Mean"))
        self.label_12.setText(_translate("AGTMultiFreqDialog", "Window size"))
        self.gBox_Output.setTitle(_translate("AGTMultiFreqDialog", "Output file"))
        self.ButtonBrowseShape.setText(_translate("AGTMultiFreqDialog", "browse"))
        self.outputLabel.setText(_translate("AGTMultiFreqDialog", "Shapefile"))
        self.label_georefscr.setText(_translate("AGTMultiFreqDialog", "CRS projection"))
        self.label_georefscr_2.setText(_translate("AGTMultiFreqDialog", "CRS projection"))
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
