# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_magDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AGTMagDialog(object):
    def setupUi(self, AGTMagDialog):
        AGTMagDialog.setObjectName("AGTMagDialog")
        AGTMagDialog.resize(354, 556)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AGTMagDialog.sizePolicy().hasHeightForWidth())
        AGTMagDialog.setSizePolicy(sizePolicy)
        self.gridLayout_5 = QtWidgets.QGridLayout(AGTMagDialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(AGTMagDialog)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.inFileLine = QtWidgets.QLineEdit(self.groupBox_5)
        self.inFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.inFileLine.setObjectName("inFileLine")
        self.gridLayout_6.addWidget(self.inFileLine, 0, 1, 1, 1)
        self.ButtonBrowse = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowse.sizePolicy().hasHeightForWidth())
        self.ButtonBrowse.setSizePolicy(sizePolicy)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName("ButtonBrowse")
        self.gridLayout_6.addWidget(self.ButtonBrowse, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(AGTMagDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RawDecimRadioBut = QtWidgets.QRadioButton(self.groupBox_4)
        self.RawDecimRadioBut.setObjectName("RawDecimRadioBut")
        self.horizontalLayout_2.addWidget(self.RawDecimRadioBut)
        self.MedianDecimRadioBut = QtWidgets.QRadioButton(self.groupBox_4)
        self.MedianDecimRadioBut.setChecked(True)
        self.MedianDecimRadioBut.setObjectName("MedianDecimRadioBut")
        self.horizontalLayout_2.addWidget(self.MedianDecimRadioBut)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.decimSpin = QtWidgets.QSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decimSpin.sizePolicy().hasHeightForWidth())
        self.decimSpin.setSizePolicy(sizePolicy)
        self.decimSpin.setSuffix("")
        self.decimSpin.setPrefix("1/")
        self.decimSpin.setMinimum(1)
        self.decimSpin.setMaximum(100)
        self.decimSpin.setProperty("value", 10)
        self.decimSpin.setObjectName("decimSpin")
        self.horizontalLayout_2.addWidget(self.decimSpin)
        self.gridLayout_5.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(AGTMagDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.percentilechk = QtWidgets.QCheckBox(self.groupBox_2)
        self.percentilechk.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percentilechk.sizePolicy().hasHeightForWidth())
        self.percentilechk.setSizePolicy(sizePolicy)
        self.percentilechk.setObjectName("percentilechk")
        self.gridLayout_3.addWidget(self.percentilechk, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        self.medchk = QtWidgets.QCheckBox(self.groupBox_2)
        self.medchk.setChecked(True)
        self.medchk.setObjectName("medchk")
        self.gridLayout_3.addWidget(self.medchk, 0, 0, 1, 1)
        self.percentSpin = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percentSpin.sizePolicy().hasHeightForWidth())
        self.percentSpin.setSizePolicy(sizePolicy)
        self.percentSpin.setSuffix("")
        self.percentSpin.setPrefix("")
        self.percentSpin.setMinimum(0)
        self.percentSpin.setMaximum(100)
        self.percentSpin.setProperty("value", 25)
        self.percentSpin.setObjectName("percentSpin")
        self.gridLayout_3.addWidget(self.percentSpin, 3, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(AGTMagDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.polyOrdSpin = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polyOrdSpin.sizePolicy().hasHeightForWidth())
        self.polyOrdSpin.setSizePolicy(sizePolicy)
        self.polyOrdSpin.setSuffix("")
        self.polyOrdSpin.setPrefix("")
        self.polyOrdSpin.setMinimum(1)
        self.polyOrdSpin.setMaximum(3)
        self.polyOrdSpin.setProperty("value", 3)
        self.polyOrdSpin.setObjectName("polyOrdSpin")
        self.gridLayout_2.addWidget(self.polyOrdSpin, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.trendchk = QtWidgets.QCheckBox(self.groupBox_3)
        self.trendchk.setObjectName("trendchk")
        self.gridLayout_2.addWidget(self.trendchk, 0, 0, 1, 1)
        self.trendPercentileChk = QtWidgets.QCheckBox(self.groupBox_3)
        self.trendPercentileChk.setObjectName("trendPercentileChk")
        self.gridLayout_2.addWidget(self.trendPercentileChk, 3, 1, 1, 1)
        self.trendPercentileSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.trendPercentileSpinBox.setMaximum(100)
        self.trendPercentileSpinBox.setProperty("value", 25)
        self.trendPercentileSpinBox.setObjectName("trendPercentileSpinBox")
        self.gridLayout_2.addWidget(self.trendPercentileSpinBox, 3, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(AGTMagDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 1, 1, 1)
        self.thresSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresSpin.sizePolicy().hasHeightForWidth())
        self.thresSpin.setSizePolicy(sizePolicy)
        self.thresSpin.setDecimals(1)
        self.thresSpin.setSingleStep(0.1)
        self.thresSpin.setProperty("value", 1.2)
        self.thresSpin.setObjectName("thresSpin")
        self.gridLayout_4.addWidget(self.thresSpin, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 1, 1, 1)
        self.gpsSpin = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpsSpin.sizePolicy().hasHeightForWidth())
        self.gpsSpin.setSizePolicy(sizePolicy)
        self.gpsSpin.setSuffix("")
        self.gpsSpin.setPrefix("")
        self.gpsSpin.setMinimum(1)
        self.gpsSpin.setMaximum(16)
        self.gpsSpin.setProperty("value", 3)
        self.gpsSpin.setObjectName("gpsSpin")
        self.gridLayout_4.addWidget(self.gpsSpin, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.stationRmvchk = QtWidgets.QCheckBox(self.groupBox)
        self.stationRmvchk.setObjectName("stationRmvchk")
        self.gridLayout_4.addWidget(self.stationRmvchk, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 5, 0, 1, 1)
        self.widget = QtWidgets.QWidget(AGTMagDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.allProcess_button = QtWidgets.QPushButton(self.widget)
        self.allProcess_button.setObjectName("allProcess_button")
        self.horizontalLayout_3.addWidget(self.allProcess_button)
        self.gridLayout_5.addWidget(self.widget, 6, 0, 1, 1)
        self.gBox_Output = QtWidgets.QGroupBox(AGTMagDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_Output.sizePolicy().hasHeightForWidth())
        self.gBox_Output.setSizePolicy(sizePolicy)
        self.gBox_Output.setObjectName("gBox_Output")
        self.gridLayout = QtWidgets.QGridLayout(self.gBox_Output)
        self.gridLayout.setObjectName("gridLayout")
        self.outputLabel = QtWidgets.QLabel(self.gBox_Output)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayout.addWidget(self.outputLabel, 0, 0, 1, 1)
        self.outputFilename = QtWidgets.QLineEdit(self.gBox_Output)
        self.outputFilename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputFilename.setObjectName("outputFilename")
        self.gridLayout.addWidget(self.outputFilename, 0, 1, 1, 2)
        self.ButtonBrowseShape = QtWidgets.QPushButton(self.gBox_Output)
        self.ButtonBrowseShape.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseShape.setObjectName("ButtonBrowseShape")
        self.gridLayout.addWidget(self.ButtonBrowseShape, 0, 3, 1, 1)
        self.label_georefscr = QtWidgets.QLabel(self.gBox_Output)
        self.label_georefscr.setObjectName("label_georefscr")
        self.gridLayout.addWidget(self.label_georefscr, 1, 0, 1, 1)
        self.qgsProjectionSelectionExport = QgsProjectionSelectionWidget(self.gBox_Output)
        self.qgsProjectionSelectionExport.setObjectName("qgsProjectionSelectionExport")
        self.gridLayout.addWidget(self.qgsProjectionSelectionExport, 1, 1, 1, 3)
        self.datFilechkbox = QtWidgets.QCheckBox(self.gBox_Output)
        self.datFilechkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.datFilechkbox.setObjectName("datFilechkbox")
        self.gridLayout.addWidget(self.datFilechkbox, 2, 0, 1, 2)
        self.coordFieldschk = QtWidgets.QCheckBox(self.gBox_Output)
        self.coordFieldschk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.coordFieldschk.setObjectName("coordFieldschk")
        self.gridLayout.addWidget(self.coordFieldschk, 2, 2, 1, 2)
        self.gridLayout_5.addWidget(self.gBox_Output, 1, 0, 1, 1)

        self.retranslateUi(AGTMagDialog)
        QtCore.QMetaObject.connectSlotsByName(AGTMagDialog)

    def retranslateUi(self, AGTMagDialog):
        _translate = QtCore.QCoreApplication.translate
        AGTMagDialog.setWindowTitle(_translate("AGTMagDialog", "MXPDA processing - GNSS"))
        self.label.setText(_translate("AGTMagDialog", "Raw data (.asc)"))
        self.ButtonBrowse.setText(_translate("AGTMagDialog", "browse"))
        self.groupBox_4.setTitle(_translate("AGTMagDialog", "Decimation"))
        self.RawDecimRadioBut.setText(_translate("AGTMagDialog", "Raw"))
        self.MedianDecimRadioBut.setText(_translate("AGTMagDialog", "Moving median"))
        self.percentilechk.setText(_translate("AGTMagDialog", "Percentile threshold"))
        self.medchk.setText(_translate("AGTMagDialog", "Median removal"))
        self.label_2.setText(_translate("AGTMagDialog", "Polynomial order"))
        self.trendchk.setText(_translate("AGTMagDialog", "Trend removal"))
        self.trendPercentileChk.setText(_translate("AGTMagDialog", "Percentile threshold"))
        self.label_3.setText(_translate("AGTMagDialog", "Threshold"))
        self.label_8.setText(_translate("AGTMagDialog", "GNSS located on probe"))
        self.stationRmvchk.setText(_translate("AGTMagDialog", "Stationary point removal"))
        self.allProcess_button.setText(_translate("AGTMagDialog", "run"))
        self.gBox_Output.setTitle(_translate("AGTMagDialog", "Output files"))
        self.outputLabel.setText(_translate("AGTMagDialog", "Shapefile"))
        self.ButtonBrowseShape.setText(_translate("AGTMagDialog", "browse"))
        self.label_georefscr.setText(_translate("AGTMagDialog", "Export CRS projection"))
        self.datFilechkbox.setText(_translate("AGTMagDialog", "Export also as .DAT"))
        self.coordFieldschk.setText(_translate("AGTMagDialog", "Add coordinates fields"))
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
