# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_MultiFreqDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AGTMultiFreqDialog(object):
    def setupUi(self, AGTMultiFreqDialog):
        AGTMultiFreqDialog.setObjectName(_fromUtf8("AGTMultiFreqDialog"))
        AGTMultiFreqDialog.resize(508, 788)
        self.gridLayout_14 = QtGui.QGridLayout(AGTMultiFreqDialog)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.groupBox_2 = QtGui.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.radioButtonHCP = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonHCP.setChecked(True)
        self.radioButtonHCP.setObjectName(_fromUtf8("radioButtonHCP"))
        self.gridLayout_6.addWidget(self.radioButtonHCP, 0, 1, 1, 1)
        self.radioButtonVCP = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonVCP.setObjectName(_fromUtf8("radioButtonVCP"))
        self.gridLayout_6.addWidget(self.radioButtonVCP, 0, 2, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_2, 8, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 0, 2, 1, 1)
        self.gnssXShift = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gnssXShift.sizePolicy().hasHeightForWidth())
        self.gnssXShift.setSizePolicy(sizePolicy)
        self.gnssXShift.setDecimals(2)
        self.gnssXShift.setMinimum(-200.0)
        self.gnssXShift.setSingleStep(0.1)
        self.gnssXShift.setProperty("value", -0.2)
        self.gnssXShift.setObjectName(_fromUtf8("gnssXShift"))
        self.gridLayout_7.addWidget(self.gnssXShift, 0, 3, 1, 1)
        self.gnssYShift = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.gnssYShift.setMinimum(-99.0)
        self.gnssYShift.setSingleStep(0.1)
        self.gnssYShift.setProperty("value", -0.4)
        self.gnssYShift.setObjectName(_fromUtf8("gnssYShift"))
        self.gridLayout_7.addWidget(self.gnssYShift, 0, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.calibButton = QtGui.QPushButton(self.groupBox_5)
        self.calibButton.setObjectName(_fromUtf8("calibButton"))
        self.gridLayout.addWidget(self.calibButton, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.magSusceptChkBox = QtGui.QCheckBox(self.groupBox_5)
        self.magSusceptChkBox.setObjectName(_fromUtf8("magSusceptChkBox"))
        self.gridLayout.addWidget(self.magSusceptChkBox, 2, 0, 1, 3)
        self.CalibrationChkBox = QtGui.QCheckBox(self.groupBox_5)
        self.CalibrationChkBox.setObjectName(_fromUtf8("CalibrationChkBox"))
        self.gridLayout.addWidget(self.CalibrationChkBox, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(89, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        self.elecConductChkBox = QtGui.QCheckBox(self.groupBox_5)
        self.elecConductChkBox.setObjectName(_fromUtf8("elecConductChkBox"))
        self.gridLayout.addWidget(self.elecConductChkBox, 1, 0, 1, 3)
        self.conductCorrectChkBox = QtGui.QCheckBox(self.groupBox_5)
        self.conductCorrectChkBox.setEnabled(False)
        self.conductCorrectChkBox.setObjectName(_fromUtf8("conductCorrectChkBox"))
        self.gridLayout.addWidget(self.conductCorrectChkBox, 3, 2, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(77, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 3, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_5, 13, 0, 1, 1)
        self.frame = QtGui.QFrame(AGTMultiFreqDialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_georefscr_2 = QtGui.QLabel(self.frame)
        self.label_georefscr_2.setObjectName(_fromUtf8("label_georefscr_2"))
        self.gridLayout_4.addWidget(self.label_georefscr_2, 2, 0, 1, 1)
        self.comboCRSImport = QtGui.QComboBox(self.frame)
        self.comboCRSImport.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCRSImport.sizePolicy().hasHeightForWidth())
        self.comboCRSImport.setSizePolicy(sizePolicy)
        self.comboCRSImport.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboCRSImport.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.comboCRSImport.setObjectName(_fromUtf8("comboCRSImport"))
        self.gridLayout_4.addWidget(self.comboCRSImport, 2, 1, 1, 1)
        self.gridLayout_14.addWidget(self.frame, 2, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(AGTMultiFreqDialog)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ButtonBrowseData = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowseData.sizePolicy().hasHeightForWidth())
        self.ButtonBrowseData.setSizePolicy(sizePolicy)
        self.ButtonBrowseData.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseData.setObjectName(_fromUtf8("ButtonBrowseData"))
        self.gridLayout_2.addWidget(self.ButtonBrowseData, 0, 2, 1, 1)
        self.dataInFileLine = QtGui.QLineEdit(self.widget_2)
        self.dataInFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dataInFileLine.setObjectName(_fromUtf8("dataInFileLine"))
        self.gridLayout_2.addWidget(self.dataInFileLine, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.widget_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(AGTMultiFreqDialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(324, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 1, 1, 1)
        self.altSpin = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.altSpin.sizePolicy().hasHeightForWidth())
        self.altSpin.setSizePolicy(sizePolicy)
        self.altSpin.setDecimals(1)
        self.altSpin.setSingleStep(0.1)
        self.altSpin.setProperty("value", 0.3)
        self.altSpin.setObjectName(_fromUtf8("altSpin"))
        self.gridLayout_5.addWidget(self.altSpin, 0, 2, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox, 7, 0, 1, 1)
        self.widget_4 = QtGui.QWidget(AGTMultiFreqDialog)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_10 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.progressBar = QtGui.QProgressBar(self.widget_4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_10.addWidget(self.progressBar, 0, 0, 1, 1)
        self.runButton = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.gridLayout_10.addWidget(self.runButton, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.widget_4, 16, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(AGTMultiFreqDialog)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.widget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gnssInFileLine = QtGui.QLineEdit(self.widget_3)
        self.gnssInFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gnssInFileLine.setObjectName(_fromUtf8("gnssInFileLine"))
        self.gridLayout_3.addWidget(self.gnssInFileLine, 0, 1, 1, 7)
        self.ButtonBrowseGnss = QtGui.QPushButton(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonBrowseGnss.sizePolicy().hasHeightForWidth())
        self.ButtonBrowseGnss.setSizePolicy(sizePolicy)
        self.ButtonBrowseGnss.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseGnss.setObjectName(_fromUtf8("ButtonBrowseGnss"))
        self.gridLayout_3.addWidget(self.ButtonBrowseGnss, 0, 8, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 6, 1, 1)
        self.gnssHourShift = QtGui.QSpinBox(self.widget_3)
        self.gnssHourShift.setMinimum(-99999)
        self.gnssHourShift.setMaximum(99999)
        self.gnssHourShift.setObjectName(_fromUtf8("gnssHourShift"))
        self.gridLayout_3.addWidget(self.gnssHourShift, 2, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.gnssSecondsShift = QtGui.QDoubleSpinBox(self.widget_3)
        self.gnssSecondsShift.setMinimum(-60.0)
        self.gnssSecondsShift.setMaximum(60.0)
        self.gnssSecondsShift.setObjectName(_fromUtf8("gnssSecondsShift"))
        self.gridLayout_3.addWidget(self.gnssSecondsShift, 2, 7, 1, 1)
        self.gnssMinuteShift = QtGui.QSpinBox(self.widget_3)
        self.gnssMinuteShift.setMinimum(-60)
        self.gnssMinuteShift.setMaximum(60)
        self.gnssMinuteShift.setObjectName(_fromUtf8("gnssMinuteShift"))
        self.gridLayout_3.addWidget(self.gnssMinuteShift, 2, 5, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 2, 2, 1, 1)
        self.gridLayout_14.addWidget(self.widget_3, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.quadChkBox = QtGui.QCheckBox(self.groupBox_4)
        self.quadChkBox.setObjectName(_fromUtf8("quadChkBox"))
        self.gridLayout_8.addWidget(self.quadChkBox, 1, 0, 1, 1)
        self.inphaseChkBox = QtGui.QCheckBox(self.groupBox_4)
        self.inphaseChkBox.setObjectName(_fromUtf8("inphaseChkBox"))
        self.gridLayout_8.addWidget(self.inphaseChkBox, 1, 1, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_4, 5, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(AGTMultiFreqDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.decimChkBox = QtGui.QCheckBox(self.groupBox_6)
        self.decimChkBox.setObjectName(_fromUtf8("decimChkBox"))
        self.gridLayout_11.addWidget(self.decimChkBox, 1, 0, 1, 1)
        self.decimSpin = QtGui.QSpinBox(self.groupBox_6)
        self.decimSpin.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decimSpin.sizePolicy().hasHeightForWidth())
        self.decimSpin.setSizePolicy(sizePolicy)
        self.decimSpin.setSuffix(_fromUtf8(""))
        self.decimSpin.setPrefix(_fromUtf8("1/"))
        self.decimSpin.setMinimum(1)
        self.decimSpin.setMaximum(100)
        self.decimSpin.setProperty("value", 5)
        self.decimSpin.setObjectName(_fromUtf8("decimSpin"))
        self.gridLayout_11.addWidget(self.decimSpin, 1, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 1, 1, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(AGTMultiFreqDialog)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        spacerItem7 = QtGui.QSpacerItem(186, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem7, 0, 1, 1, 1)
        self.windowSizeSpinIp = QtGui.QSpinBox(self.groupBox_9)
        self.windowSizeSpinIp.setEnabled(False)
        self.windowSizeSpinIp.setMaximum(500)
        self.windowSizeSpinIp.setProperty("value", 5)
        self.windowSizeSpinIp.setObjectName(_fromUtf8("windowSizeSpinIp"))
        self.gridLayout_13.addWidget(self.windowSizeSpinIp, 0, 6, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_9)
        self.label_13.setEnabled(False)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_13.addWidget(self.label_13, 0, 5, 1, 1)
        self.windowSlideMeanIp = QtGui.QRadioButton(self.groupBox_9)
        self.windowSlideMeanIp.setEnabled(False)
        self.windowSlideMeanIp.setObjectName(_fromUtf8("windowSlideMeanIp"))
        self.buttonGroup_2 = QtGui.QButtonGroup(AGTMultiFreqDialog)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.windowSlideMeanIp)
        self.gridLayout_13.addWidget(self.windowSlideMeanIp, 0, 3, 1, 1)
        self.windowSlideMedianIp = QtGui.QRadioButton(self.groupBox_9)
        self.windowSlideMedianIp.setEnabled(False)
        self.windowSlideMedianIp.setCheckable(True)
        self.windowSlideMedianIp.setChecked(True)
        self.windowSlideMedianIp.setObjectName(_fromUtf8("windowSlideMedianIp"))
        self.buttonGroup_2.addButton(self.windowSlideMedianIp)
        self.gridLayout_13.addWidget(self.windowSlideMedianIp, 0, 2, 1, 1)
        self.SlidingWindowChkBoxIp = QtGui.QCheckBox(self.groupBox_9)
        self.SlidingWindowChkBoxIp.setObjectName(_fromUtf8("SlidingWindowChkBoxIp"))
        self.gridLayout_13.addWidget(self.SlidingWindowChkBoxIp, 0, 0, 1, 1)
        self.SlidingWindowChkBoxQ = QtGui.QCheckBox(self.groupBox_9)
        self.SlidingWindowChkBoxQ.setChecked(False)
        self.SlidingWindowChkBoxQ.setTristate(False)
        self.SlidingWindowChkBoxQ.setObjectName(_fromUtf8("SlidingWindowChkBoxQ"))
        self.gridLayout_13.addWidget(self.SlidingWindowChkBoxQ, 1, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(436, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem8, 1, 1, 1, 1)
        self.windowSlideMedianQ = QtGui.QRadioButton(self.groupBox_9)
        self.windowSlideMedianQ.setEnabled(False)
        self.windowSlideMedianQ.setCheckable(True)
        self.windowSlideMedianQ.setChecked(True)
        self.windowSlideMedianQ.setObjectName(_fromUtf8("windowSlideMedianQ"))
        self.buttonGroup = QtGui.QButtonGroup(AGTMultiFreqDialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.windowSlideMedianQ)
        self.gridLayout_13.addWidget(self.windowSlideMedianQ, 1, 2, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton.setEnabled(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout_13.addWidget(self.radioButton, 1, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_9)
        self.label_12.setEnabled(False)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_13.addWidget(self.label_12, 1, 5, 1, 1)
        self.windowSizeSpinQ = QtGui.QSpinBox(self.groupBox_9)
        self.windowSizeSpinQ.setEnabled(False)
        self.windowSizeSpinQ.setMaximum(500)
        self.windowSizeSpinQ.setProperty("value", 5)
        self.windowSizeSpinQ.setObjectName(_fromUtf8("windowSizeSpinQ"))
        self.gridLayout_13.addWidget(self.windowSizeSpinQ, 1, 6, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_9, 6, 0, 1, 1)
        self.gBox_Output = QtGui.QGroupBox(AGTMultiFreqDialog)
        self.gBox_Output.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_Output.sizePolicy().hasHeightForWidth())
        self.gBox_Output.setSizePolicy(sizePolicy)
        self.gBox_Output.setObjectName(_fromUtf8("gBox_Output"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gBox_Output)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.ButtonBrowseShape = QtGui.QPushButton(self.gBox_Output)
        self.ButtonBrowseShape.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowseShape.setObjectName(_fromUtf8("ButtonBrowseShape"))
        self.gridLayout_12.addWidget(self.ButtonBrowseShape, 0, 3, 1, 1)
        self.outputLabel = QtGui.QLabel(self.gBox_Output)
        self.outputLabel.setObjectName(_fromUtf8("outputLabel"))
        self.gridLayout_12.addWidget(self.outputLabel, 0, 0, 1, 1)
        self.label_georefscr = QtGui.QLabel(self.gBox_Output)
        self.label_georefscr.setObjectName(_fromUtf8("label_georefscr"))
        self.gridLayout_12.addWidget(self.label_georefscr, 2, 0, 1, 1)
        self.outputFilename = QtGui.QLineEdit(self.gBox_Output)
        self.outputFilename.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputFilename.setObjectName(_fromUtf8("outputFilename"))
        self.gridLayout_12.addWidget(self.outputFilename, 0, 1, 1, 1)
        self.comboCRS = QtGui.QComboBox(self.gBox_Output)
        self.comboCRS.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCRS.sizePolicy().hasHeightForWidth())
        self.comboCRS.setSizePolicy(sizePolicy)
        self.comboCRS.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboCRS.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.comboCRS.setObjectName(_fromUtf8("comboCRS"))
        self.gridLayout_12.addWidget(self.comboCRS, 2, 1, 1, 2)
        self.gridLayout_14.addWidget(self.gBox_Output, 15, 0, 1, 1)

        self.retranslateUi(AGTMultiFreqDialog)
        QtCore.QObject.connect(self.SlidingWindowChkBoxQ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.windowSlideMedianQ.setEnabled)
        QtCore.QObject.connect(self.SlidingWindowChkBoxQ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.windowSizeSpinQ.setEnabled)
        QtCore.QObject.connect(self.SlidingWindowChkBoxQ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.radioButton.setEnabled)
        QtCore.QObject.connect(self.SlidingWindowChkBoxQ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_12.setEnabled)
        QtCore.QObject.connect(self.SlidingWindowChkBoxIp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.windowSlideMedianIp.setEnabled)
        QtCore.QObject.connect(self.SlidingWindowChkBoxIp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.windowSlideMeanIp.setEnabled)
        QtCore.QObject.connect(self.SlidingWindowChkBoxIp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_13.setEnabled)
        QtCore.QObject.connect(self.SlidingWindowChkBoxIp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.windowSizeSpinIp.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(AGTMultiFreqDialog)

    def retranslateUi(self, AGTMultiFreqDialog):
        AGTMultiFreqDialog.setWindowTitle(_translate("AGTMultiFreqDialog", "GEM2 / EMP400", None))
        self.label_4.setText(_translate("AGTMultiFreqDialog", "Coils geometry", None))
        self.radioButtonHCP.setText(_translate("AGTMultiFreqDialog", "HCP (vertical dipole)", None))
        self.radioButtonVCP.setText(_translate("AGTMultiFreqDialog", "VCP (horizontal dipole)", None))
        self.label_5.setText(_translate("AGTMultiFreqDialog", "Spatial shift/GNSS", None))
        self.label_6.setText(_translate("AGTMultiFreqDialog", "X", None))
        self.label_7.setText(_translate("AGTMultiFreqDialog", "Y", None))
        self.groupBox_5.setTitle(_translate("AGTMultiFreqDialog", "Physical parameters computation", None))
        self.calibButton.setText(_translate("AGTMultiFreqDialog", "Calibration parameters", None))
        self.magSusceptChkBox.setText(_translate("AGTMultiFreqDialog", "Magnetic susceptibility", None))
        self.CalibrationChkBox.setText(_translate("AGTMultiFreqDialog", "Calibration", None))
        self.elecConductChkBox.setText(_translate("AGTMultiFreqDialog", "Electrical conductivity", None))
        self.conductCorrectChkBox.setText(_translate("AGTMultiFreqDialog", "Conductivity correction of In Phase", None))
        self.label_georefscr_2.setText(_translate("AGTMultiFreqDialog", "CRS projection", None))
        self.ButtonBrowseData.setText(_translate("AGTMultiFreqDialog", "browse", None))
        self.label.setText(_translate("AGTMultiFreqDialog", "Raw data", None))
        self.label_3.setText(_translate("AGTMultiFreqDialog", "Device height (m)", None))
        self.runButton.setText(_translate("AGTMultiFreqDialog", "run", None))
        self.label_2.setText(_translate("AGTMultiFreqDialog", "GNSS data (.dat)", None))
        self.ButtonBrowseGnss.setText(_translate("AGTMultiFreqDialog", "browse", None))
        self.label_11.setText(_translate("AGTMultiFreqDialog", "Seconds:", None))
        self.label_10.setText(_translate("AGTMultiFreqDialog", "Minutes:", None))
        self.label_8.setText(_translate("AGTMultiFreqDialog", "GNSS Time Shift", None))
        self.label_9.setText(_translate("AGTMultiFreqDialog", "Hours:", None))
        self.groupBox_4.setTitle(_translate("AGTMultiFreqDialog", "Median removal (by profile)", None))
        self.quadChkBox.setText(_translate("AGTMultiFreqDialog", "Quadrature", None))
        self.inphaseChkBox.setText(_translate("AGTMultiFreqDialog", "In-phase", None))
        self.groupBox_6.setTitle(_translate("AGTMultiFreqDialog", "Decimation", None))
        self.decimChkBox.setText(_translate("AGTMultiFreqDialog", "Decimation", None))
        self.groupBox_9.setTitle(_translate("AGTMultiFreqDialog", "Sliding Window", None))
        self.label_13.setText(_translate("AGTMultiFreqDialog", "Window size", None))
        self.windowSlideMeanIp.setText(_translate("AGTMultiFreqDialog", "Mean", None))
        self.windowSlideMedianIp.setText(_translate("AGTMultiFreqDialog", "Median", None))
        self.SlidingWindowChkBoxIp.setText(_translate("AGTMultiFreqDialog", "In-phase filtering", None))
        self.SlidingWindowChkBoxQ.setText(_translate("AGTMultiFreqDialog", "Quadrature filtering", None))
        self.windowSlideMedianQ.setText(_translate("AGTMultiFreqDialog", "Median", None))
        self.radioButton.setText(_translate("AGTMultiFreqDialog", "Mean", None))
        self.label_12.setText(_translate("AGTMultiFreqDialog", "Window size", None))
        self.gBox_Output.setTitle(_translate("AGTMultiFreqDialog", "Output file", None))
        self.ButtonBrowseShape.setText(_translate("AGTMultiFreqDialog", "browse", None))
        self.outputLabel.setText(_translate("AGTMultiFreqDialog", "Shapefile", None))
        self.label_georefscr.setText(_translate("AGTMultiFreqDialog", "CRS projection", None))

